In [1]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
import matplotlib.pyplot as plt

# from sklearn.model_selection import StratifiedShuffleSplit
# from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_curve, roc_auc_score

import glob
import pickle

import warnings
warnings.filterwarnings('ignore')

In [2]:
path = '/data/national_nutrition/*_all.sas7bdat'

In [3]:
sorted(glob.glob(path))

['/data/national_nutrition/hn01_all.sas7bdat',
 '/data/national_nutrition/hn05_all.sas7bdat',
 '/data/national_nutrition/hn07_all.sas7bdat',
 '/data/national_nutrition/hn08_all.sas7bdat',
 '/data/national_nutrition/hn09_all.sas7bdat',
 '/data/national_nutrition/hn10_all.sas7bdat',
 '/data/national_nutrition/hn11_all.sas7bdat',
 '/data/national_nutrition/hn12_all.sas7bdat',
 '/data/national_nutrition/hn13_all.sas7bdat',
 '/data/national_nutrition/hn14_all.sas7bdat',
 '/data/national_nutrition/hn15_all.sas7bdat',
 '/data/national_nutrition/hn16_all.sas7bdat',
 '/data/national_nutrition/hn17_all.sas7bdat',
 '/data/national_nutrition/hn18_all.sas7bdat',
 '/data/national_nutrition/hn19_all.sas7bdat',
 '/data/national_nutrition/hn20_all.sas7bdat',
 '/data/national_nutrition/hn98_all.sas7bdat']

# Data Load

비타민D 대상자: (2008 ~ 2012년) 만10세이상 전수, (2013 ~ 2014년) 만10세이상 2,400명
- 비타민D: HE_vitD

In [4]:
df8 = pd.read_sas('/data/national_nutrition/hn08_all.sas7bdat')
df9 = pd.read_sas('/data/national_nutrition/hn09_all.sas7bdat')
df10 = pd.read_sas('/data/national_nutrition/hn10_all.sas7bdat')
df11 = pd.read_sas('/data/national_nutrition/hn11_all.sas7bdat')
df12 = pd.read_sas('/data/national_nutrition/hn12_all.sas7bdat')
df13 = pd.read_sas('/data/national_nutrition/hn13_all.sas7bdat')
df14 = pd.read_sas('/data/national_nutrition/hn14_all.sas7bdat')

In [5]:
common_columns = df8.columns.intersection(df9.columns).intersection(df10.columns).intersection(df11.columns).intersection(df12.columns).intersection(df13.columns).intersection(df14.columns)

In [6]:
df_temp = pd.concat([df8[common_columns], df9[common_columns]])
df_temp = pd.concat([df_temp, df10[common_columns]])
df_temp = pd.concat([df_temp, df11[common_columns]])
df_temp = pd.concat([df_temp, df12[common_columns]])
df_temp = pd.concat([df_temp, df13[common_columns]])
df = pd.concat([df_temp, df14[common_columns]])

df = df[df['age'] >= 10]
df[['HE_vitD']].isna().sum()
df = df.dropna(subset=['HE_vitD'], axis=0) # HE_vitD 결측치 제거
df = df.reset_index(drop=True)
# df

In [7]:
df

,mod_d,id,year,region,town_t,apt_t,psu,sex,age,incm,...,N_FE,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC
0,b'2022.03.08',b'A448440901',2008.0,1.0,1.0,1.0,b'A448',1.0,70.0,2.0,...,15.556678,7472.249217,4895.631231,881.735572,5273.157673,2.203960,1.561326,0.987078,16.272761,262.812776
1,b'2022.03.08',b'A448440902',2008.0,1.0,1.0,1.0,b'A448',2.0,68.0,2.0,...,11.758635,4430.090787,3680.878220,777.813158,4646.511191,2.188609,1.116872,0.729980,11.567262,206.477449
2,b'2022.03.08',b'A448680102',2008.0,1.0,1.0,1.0,b'A448',2.0,48.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,b'2022.03.08',b'A448680501',2008.0,1.0,1.0,1.0,b'A448',2.0,35.0,3.0,...,18.839099,2684.503728,3310.676976,1932.710046,10725.673284,144.044389,0.909731,1.101102,9.129266,147.954071
4,b'2022.03.08',b'A448680502',2008.0,1.0,1.0,1.0,b'A448',1.0,12.0,3.0,...,6.087956,2796.580638,2984.102868,434.816014,571.273052,166.161773,1.212672,1.752693,8.201845,65.331394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,b'2022.03.08',b'P246808014',2014.0,16.0,1.0,2.0,b'P246',1.0,10.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39755,b'2022.03.08',b'P246808015',2014.0,16.0,1.0,2.0,b'P246',2.0,39.0,4.0,...,9.125954,3685.879396,1880.994894,1933.891026,1906.202132,1615.497101,2.497810,1.278473,14.143210,36.145233
39756,b'2022.03.08',b'P246811414',2014.0,16.0,1.0,2.0,b'P246',1.0,30.0,3.0,...,6.913193,2043.568097,1147.876072,300.249632,1793.774635,0.983537,0.791706,0.511638,6.020183,27.892272
39757,b'2022.03.08',b'P246811416',2014.0,16.0,1.0,2.0,b'P246',1.0,58.0,3.0,...,14.437036,1758.339159,1446.924818,189.142622,1124.184551,1.043302,1.490047,0.384598,8.750881,24.329294
39758,b'2022.03.08',b'P246816515',2014.0,16.0,1.0,2.0,b'P246',2.0,63.0,2.0,...,17.755221,4135.396263,3929.953846,1128.278822,6215.580482,90.872025,2.617619,1.530583,13.680425,126.004317

# Preprocessing

## 특정컬럼 제거

- 데이터가 전부 nan인 컬럼 제거

In [8]:
l1 = []
for col in df.columns:
    if df[col].isnull().sum() == 39759:
        #print(col)
        l1.append(col)
print(l1)
print(len(l1))
df = df.drop(columns = l1)

['Y_BTH_WT', 'Y_MTM_YN', 'Y_MTM_S1', 'Y_MTM_D1', 'Y_MTM_S2', 'Y_MTM_D2', 'Y_FM_YN', 'Y_FM_S1', 'Y_FM_D1', 'Y_FM_S2', 'Y_FM_D2', 'Y_MLK_ST', 'Y_WN_ST', 'Y_SUP_YN', 'Y_SUP_KD1', 'Y_SUP_KD3', 'Y_SUP_KD4', 'Y_SUP_KD7']
18

- 쓸수 없는 컬럼 제거

In [9]:
df_col_info = pd.read_csv('국건영(지침서)_copy.csv')

In [10]:
## 실행 주의 ## 
l2 = []
for i in df.columns[2:143]:
    if i not in list(df_col_info['variable'][:130]):
        l2.append(i)
print(l2)
df = df.drop(columns = l2)

['psu', 'kstrata', 'wt_hs', 'wt_pft', 'wt_ntr', 'wt_itvex', 'wt_tot', 'wt_pfnt', 'ID_fam', 'DE1_35', 'DC11_tp']

## object type 변수 삭제 및 변수 재배치

In [11]:
df.dtypes[df.dtypes == object].index

Index(['mod_d', 'id', 'BH1_7', 'BH2_65', 'LQ4_24', 'EC1_2_1', 'EC_wht_6',
       'BO3_11', 'BM12_2', 'N_DT_DS', 'N_DUSUAL'],
      dtype='object')

In [12]:
drop_col = list(df.dtypes[df.dtypes == object].index) + ['HE_vitD','ainc_1','ainc_unit1'] #소득변수 포함
vitD = df['HE_vitD']

In [13]:
df = df.drop(columns=drop_col)

In [14]:
df['HE_vitD'] = vitD

In [15]:
df.head()

,year,region,town_t,apt_t,sex,age,incm,ho_incm,incm5,ho_incm5,...,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC,HE_vitD
0,2008.0,1.0,1.0,1.0,1.0,70.0,2.0,1.0,2.0,1.0,...,7472.249217,4895.631231,881.735572,5273.157673,2.203960,1.561326,0.987078,16.272761,262.812776,14.85
1,2008.0,1.0,1.0,1.0,2.0,68.0,2.0,1.0,2.0,1.0,...,4430.090787,3680.878220,777.813158,4646.511191,2.188609,1.116872,0.729980,11.567262,206.477449,14.05
2,2008.0,1.0,1.0,1.0,2.0,48.0,4.0,4.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.36
3,2008.0,1.0,1.0,1.0,2.0,35.0,3.0,3.0,3.0,4.0,...,2684.503728,3310.676976,1932.710046,10725.673284,144.044389,0.909731,1.101102,9.129266,147.954071,18.52
4,2008.0,1.0,1.0,1.0,1.0,12.0,3.0,3.0,4.0,4.0,...,2796.580638,2984.102868,434.816014,571.273052,166.161773,1.212672,1.752693,8.201845,65.331394,18.47

## 비해당, 모름(8,88,888,,) 구분

In [16]:
df_col_info

,variable,variable description,option description,data type
0,year,조사연도,2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 |,numeric
1,region,16개 시도,1 : 서울 | 2 : 부산 | 3 : 대구 | 4 : 인천 | 5 : 광주 | 6...,category
2,town_t,동/읍면 구분,1 : 동 | 2 : 읍·면 |,category
3,apt_t,아파트 구분,1 : 일반 | 2 : 아파트 |,category
4,sex,성별,1 : 남자 | 2 : 여자 |,category
...,...,...,...,...
403,N_RETIN,레티놀,NaN,numeric
404,N_B1,티아민,NaN,numeric
405,N_B2,리보플라빈,NaN,numeric
406,N_NIAC,나이아신,NaN,numeric
407,N_VITC,비타민C,NaN,numeric

In [17]:
df_col_info = df_col_info[df_col_info['variable'].map(lambda x: x not in l1)] # 유아 관련 nan값
df_col_info = df_col_info[df_col_info['variable'].map(lambda x: x not in drop_col)] # 위에서 제거한 열
df_col_info

,variable,variable description,option description,data type
0,year,조사연도,2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 |,numeric
1,region,16개 시도,1 : 서울 | 2 : 부산 | 3 : 대구 | 4 : 인천 | 5 : 광주 | 6...,category
2,town_t,동/읍면 구분,1 : 동 | 2 : 읍·면 |,category
3,apt_t,아파트 구분,1 : 일반 | 2 : 아파트 |,category
4,sex,성별,1 : 남자 | 2 : 여자 |,category
...,...,...,...,...
403,N_RETIN,레티놀,NaN,numeric
404,N_B1,티아민,NaN,numeric
405,N_B2,리보플라빈,NaN,numeric
406,N_NIAC,나이아신,NaN,numeric
407,N_VITC,비타민C,NaN,numeric

### 기준 다른 변수 처리

In [18]:
# 소득금액 기준 1:연 2:월

# 2008-2009
ind_07_09 = df['ainc'][(df['year']==2007.0) & (df['year']==2009.0)].index


# 2010-2012
ind_10_12 = df['ainc'][(df['year']>=2010.0) & (df['year']<=2012.0)].index


# 2013-2014
ind_13_14 = df['ainc'][(df['year']==2013.0) | (df['year']==2014.0)].index


        
for ind in ind_10_12: # 연
    if (df['ainc'].iloc[ind] > 1) & (df['ainc'].iloc[ind] <= 17):
        df['ainc'].iloc[ind] = 17
    elif df['ainc'].iloc[ind] >= 900:
        df['ainc'].iloc[ind] = 900
    else:
        pass
        
for ind in ind_13_14: # 월
    if (df['ainc'].iloc[ind] >= 900):
        df['ainc'].iloc[ind] = 900

In [19]:
lst_2_0 = ['BM12', 'OR1_2'] # 치과진료 미검진 여부 , 1년간 구강검진 여부
for col in df.columns:
    if col in lst_2_0:
        df.loc[df[col] == 2, col] = 0
df['BM12'].value_counts()
df['OR1_2'].value_counts()

0.0    27754
1.0    10989
9.0      389
Name: OR1_2, dtype: int64

### 범주형 변수

In [20]:
df_col_cat = df_col_info[df_col_info['data type']=='category']
df_col_cat['data type'].unique()

array(['category'], dtype=object)

In [21]:
df_col_cat

,variable,variable description,option description,data type
1,region,16개 시도,1 : 서울 | 2 : 부산 | 3 : 대구 | 4 : 인천 | 5 : 광주 | 6...,category
2,town_t,동/읍면 구분,1 : 동 | 2 : 읍·면 |,category
3,apt_t,아파트 구분,1 : 일반 | 2 : 아파트 |,category
4,sex,성별,1 : 남자 | 2 : 여자 |,category
6,incm,소득 사분위수(개인),1 : 하 | 2 : 중하 | 3 : 중상 | 4 : 상 |,category
...,...,...,...,...
364,LK_EDU,영양교육 여부,1:예|2:아니오|9:모름/무응답,category
365,LF_CARE,식생활지원프로그램 수혜경험,1:예|2:아니오|9:모름/무응답,category
366,LF_SAFE,식생활형편,1: 충분한 양과 다양한 음식 먹을 수 있었다|2:충분한 양의 음식을 먹을 수 있었...,category
386,N_DIET,식이요법여부,1:예|2:아니오|9:모름/무응답,category
387,N_DIET_WHY,식이요법이유,1:질환이 있어서|2:체중을 조절하기 위해서|3:기타|8:비해당|9:모름/무응답,category

In [22]:
df_col_cat_list = list(df_col_cat['variable'])

df_f2s = df[df_col_cat_list].copy()
df_f2s

,region,town_t,apt_t,sex,incm,ho_incm,incm5,ho_incm5,edu,occp,...,O_DFID,O_DMFIP,L_OUT_FQ,LK_LB_IT,LK_LB_EF,LK_EDU,LF_CARE,LF_SAFE,N_DIET,N_DIET_WHY
0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,...,0.0,1.0,3.0,88.0,8.0,2.0,2.0,2.0,2.0,8.0
1,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,7.0,...,0.0,1.0,3.0,88.0,8.0,2.0,2.0,2.0,1.0,2.0
2,1.0,1.0,1.0,2.0,4.0,4.0,5.0,5.0,3.0,7.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,1.0,2.0,3.0,3.0,3.0,4.0,3.0,7.0,...,0.0,1.0,3.0,1.0,2.0,2.0,2.0,1.0,2.0,8.0
4,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,1.0,NaN,...,0.0,0.0,3.0,88.0,8.0,1.0,2.0,1.0,2.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,16.0,1.0,2.0,1.0,4.0,4.0,5.0,5.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39755,16.0,1.0,2.0,2.0,4.0,4.0,5.0,5.0,4.0,7.0,...,NaN,NaN,3.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0
39756,16.0,1.0,2.0,1.0,3.0,3.0,3.0,4.0,4.0,3.0,...,NaN,NaN,3.0,88.0,8.0,2.0,2.0,2.0,1.0,2.0
39757,16.0,1.0,2.0,1.0,3.0,3.0,3.0,4.0,3.0,6.0,...,NaN,NaN,6.0,8.0,1.0,2.0,2.0,2.0,2.0,8.0
39758,16.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,3.0,...,NaN,NaN,1.0,88.0,8.0,2.0,2.0,1.0,1.0,2.0

In [23]:
tmp = []
for i in df_col_cat.index:
    if df_col_cat.loc[i]['variable'] not in df.columns:
        tmp.append(i)
df_col_cat.drop(tmp,axis = 0,inplace = True)

In [24]:
df_col_cat.head()

,variable,variable description,option description,data type
1,region,16개 시도,1 : 서울 | 2 : 부산 | 3 : 대구 | 4 : 인천 | 5 : 광주 | 6...,category
2,town_t,동/읍면 구분,1 : 동 | 2 : 읍·면 |,category
3,apt_t,아파트 구분,1 : 일반 | 2 : 아파트 |,category
4,sex,성별,1 : 남자 | 2 : 여자 |,category
6,incm,소득 사분위수(개인),1 : 하 | 2 : 중하 | 3 : 중상 | 4 : 상 |,category

`df_f2s` : `df` 의 범주형 변수의 값들을 문자형으로 변경한 데이터

`dic_float2str` : 범주형 변수의 값을 문자형으로 변경할 때 사용한 딕셔너리

In [25]:
# float to string
f2s_dic_list= {}
for i in range(len(df_col_cat)):
    
        val_name = df_col_cat.iloc[i][0]          # 변수명
        option = df_col_cat.iloc[i][2]            # option 값들, ex)1 : 일반 | 2 : 아파트 |
        
        if option[-1] == '|':
            option = option[:-1]
        
        option = option.split('|')
        dic_float2str = {}
        
        for i in option:
            print(i)
            k,v = i.split(':')
            dic_float2str[float(k.strip())] = v.strip()
            
        f2s_dic_list[val_name] = dic_float2str
        df_f2s[val_name] = df_f2s[val_name].map(dic_float2str)

1 : 서울
 2 : 부산
 3 : 대구
 4 : 인천
 5 : 광주
 6 : 대전
 7 : 울산
 8 : 세종
 9 : 경기
 10 : 강원
 11 : 충북
 12 : 충남
 13 : 전북
 14 : 전남
 15 : 경북
 16 : 경남
 17 : 제주
1 : 동
 2 : 읍·면
1 : 일반
 2 : 아파트
1 : 남자
 2 : 여자
1 : 하
 2 : 중하
 3 : 중상
 4 : 상
1 : 하
 2 : 중하
 3 : 중상
 4 : 상
1 : 하
 2 : 중하
 3 : 중
 4 : 중상
 5 : 상
1 : 하
 2 : 중하
 3 : 중
 4 : 중상
 5 : 상
1 : 초졸이하
 2 : 중졸
 3 : 고졸
 4 : 대졸이상
1 : 관리자, 전문가 및 관련 종사자
 2 : 사무종사자
 3 : 서비스 및 판매 종사자
 4 : 농림어업 숙련 종사자
 5 : 기능원, 장치?기계조작 및 조립종사자
 6 : 단순노무종사자
 7 : 무직(주부, 학생 등)
1 : 1명
 2 : 2명
 3 : 3명
 4 : 4명
 5 : 5명
 6 : 6명 이상
 9 : 모름, 무응답
1 : 1세대 가구 - 1인가구
 2 : 1세대 가구 - 부부
 3 : 1세대 가구 - 기타
 4 : 2세대 가구 - 부부+미혼자녀
 5 : 2세대 가구 ? 편부모+미혼자녀
 6 : 2세대 가구 ? 기타
 7 : 3세대 이상 가구
 9 : 모름, 무응답
10 : 수급경험 있음(과거 또는 현재)
 20 : 수급경험 없음
 99 : 모름, 무응답
1 : 아니오
 2 : 1채 있음
 3 : 2채 이상 있음
 9 : 모름, 무응답
1 : 단독주택
 2 : 아파트
 3 : 연립주택
 4 : 다세대 주택
 5 : 기타
 9 : 모름, 무응답
1 : 기혼
 2 : 미혼
 9 : 모름, 무응답
1 : 유배우자, 동거
 2 : 유배우자, 별거
 3 : 사별
 4 : 이혼
 8 : 응답거부
 9 : 모름
 88 : 비해당(문항10-E)
 99 : 무응답
10 : 국민건강보험(지역)
 20 : 국민건강보험(직장)
 30 : 의료급여
 99 : 미가입, 모름, 무응답
1 : 예
 2 : 아니오
 9 : 모름
 99 : 무응답
1 : 매우 좋음
 2 : 좋음
 3 : 보통
 4 : 나쁨
 5 : 매우 나쁨
 9 : 모름, 무응답
1 : 예
 2 : 아니오
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
1 : 매일 복용함
 2 : 한달에 20일 이상 복용함
 3 : 한달에 15일 이상 복용함
 4 : 한달에 15일 미만 복용함
 5 : 복용하지 않음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
1 : 매일 복용함
 2 : 한달에 20일 이상 복용함
 3 : 한달에 15일 이상 복용함
 4 : 한달에 15일 미만 복용함
 5 : 복용하지 않음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
1 : 후유증을 앓고 있음
 2 : 후유증이 있었지만 지금은 회복되었음
 3 : 특별한 후유증이 없음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 지금까지 앓은 적 없음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
1 : 악화방지 및 천식증상관리를 위해 정기적으로 치료를 받음
 2 : 증상이 있을 때만 치료를 받음
 3 : 치료받지 않음
 8 : 비해당(의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(지금까지 앓은 적 없음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
1 : 예
 2 : 아니오
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 아니오
 1 : 예
 8 : 비해당(지금까지 앓은 적 없음)
 9 : 모름, 무응답
0 : 아니오
 1 : 예
 8 : 비해당(문항14-5-②⑧)
 9 : 모름, 무응답
0 : 아니오
 1 : 예
 8 : 비해당(문항14-5-②⑧)
 9 : 모름, 무응답
0 : 아니오
 1 : 예
 8 : 비해당(문항14-5-②⑧)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아)
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당(청소년, 소아, 의사진단 받지 않음)
 9 : 모름, 무응답
0 : 없음
 1: 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1: 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
0 : 없음
 1 : 있음
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
1 : 예
 2 : 아니오
 9 : 모름, 무응답
1 : 예
 2 : 아니오
 8 : 직장 또는 학교에 다니지 않음
 9 : 모름, 무응답
1 :  나는 걷는데 지장이 없음
 2 : 나는 걷는데 다소 지장이 있음
 3 : 나는 종일 누워 있어야 함
 8 : 비해당(소아청소년)
 9 : 모름
1 : 나는 목욕을 하거나 옷을 입는데 지장이 없음
 2 : 나는 혼자 목욕을 하거나 옷을 입는데 다소 지장이 있음
 3 : 나는 혼자 목욕을 하거나 옷을 입을 수 없음
 8 : 비해당(소아청소년)
 9 : 모름
1 : 나는 일상활동을 하는데 지장 없음
 2 : 나는 일상활동을 하는데 다소 지장 있음
 3 : 나는 일상활동을 할 수 없음
 8 : 비해당(소아청소년)
 9 : 모름
1 : 나는 통증/불편감이 없음
 2 : 나는 다소 통증/불편감이 있음
 3 : 나는 매우 심한 통증/불편감 있음
 8 : 비해당(소아청소년)
 9 : 모름
1 : 나는 불안하거나 우울하지 않음
 2 : 나는 다소 불안하거나 우울함
 3 : 나는 매우 심하게 불안하거나 우울함
 8 : 비해당(소아청소년)
 9 : 모름
1 : 미취학
 2 : 서당
 3 : 무학
 4 : 초등학교
 5 : 중학교
 6 : 고등학교
 7: 2/3년제 대학
 8 : 4년제 대학
 9 : 대학원
 88 : 소아
 99 : 모름
1 : 졸업
 2 : 수료
 3 : 중퇴
 4 : 재학/휴학 중
 8 : 비해당
 9 : 모름, 무응답
1 : 유치원
 2 : 초등학교
 3 : 중학교
 4 : 미취학
 8 : 비해당
 9 : 모름, 무응답
1 : 졸업
 2 : 수료
 3 : 중퇴
 4 : 재학/휴학 중
 8 : 비해당
 9 : 모름, 무응답
1 : 예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 : 필요를 느끼지 못해
 2 : 학교/학원 재직중
 3 : 정년/퇴직 상태
 4 : 건강상의 이유
 5 : 실업/구직 중
 6 : 육아/간병
 7 : 기타
 8 : 비해당
 9 : 모름, 무응답
1 : 임금근로자
 2 : 자영업자와 고용주
 3 : 무급가족종사자
 8 : 비해당
 9 : 모름, 무응답
1 : 상용직
 2 : 임시직
 3 : 일용직
 8 : 비해당
 9 : 모름, 무응답
1 : 전일제
 2 : 시간제
 8 : 비해당
 9 : 모름, 무응답
1 : 관리자
 2 : 전문가 및 관련 종사자
 3 : 사무종사자
 4 : 서비스종사자
 5 : 판매종사자
 6 : 농림어업숙련종사자
 7 : 기능원 및 관련기능 종사자
 8 : 장치, 기계조작 및 조립종사자
 9 : 단순노무종사자
 10 : 군인
 88 : 비해당
 99 : 모름
1 : 관리자
 2 : 전문가 및 관련 종사자
 3 : 사무종사자
 4 : 서비스종사자
 5 : 판매종사자
 6 : 농림어업숙련종사자
 7 : 기능원 및 관련기능 종사자
 8 : 장치, 기계조작 및 조립종사자
 9 : 단순노무종사자
 10 : 군인
 88 : 비해당
 99 : 모름
1 : 임금근로자
 2 : 자영업주
 3 : 무급가족종사자
 8 : 비해당
 9 : 모름, 무응답
1 : 상용직
 2 : 임시직
 3 : 일용직
 8 : 비해당
 9 : 모름, 무응답
1 : 무학
 2 : 서당
 3 : 초등학교
 4 : 중학교
 5 : 고등학교
 6 : 2/3년제 대학
 7 : 4년제 대학
 8 : 대학원
 88 : 비해당
 99 : 모름
1 : 무학
 2 : 서당
 3 : 초등학교
 4 : 중학교
 5 : 고등학교
 6 : 2/3년제 대학
 7 : 4년제 대학
 8 : 대학원
 88 : 비해당
 99 : 모름
1 : 주간 근무
 2 : 저녁 근무
 3 : 밤 근무
 4 : 주야간 규칙적 교대근무
 5 : 24시간 교대근무
 6 : 분할근무
 7 : 불규칙 교대근무
 8 : 기타
 88 : 비해당
 99 : 모름
1 : 매우 마른 편
 2 : 약간 마른 편
 3 : 보통
 4 : 약간 비만
 5 : 매우 비만
 8 : 비해당
 9 : 모름, 무응답
1 : 변화 없음
 2 : 체중 감소
 3 : 체중 증가
 8 : 비해당
 9 : 모름, 무응답
1 : 3kg - 6kg 미만
 2 : 6kg - 10kg
 3 : 10kg 이상
 8 : 비해당
 9 : 모름, 무응답
1 : 3kg - 6kg 미만
 2 : 6kg - 10kg
 3 : 10kg 이상
 8 : 비해당
 9 : 모름, 무응답
1 : 체중 감소 노력
 2 : 체중 유지 노력
 3 : 체중 증가 노력
 4 : 체중 조절 노력해본 적 없음
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
0 :  아니오
 1 : 예
 8 : 비해당
 9 : 모름, 무응답
1 : 술을 마셔 본 적 없음
 2 : 있음
 8 : 비해당
 9 : 모름, 무응답
1 : 최근 1년간 마시지 않음
 2 : 월1회미만
 3 : 월1회정도
 4 : 월2-4회
 5 : 주2-3회정도
 6 : 주4회이상
 8 : 비해당
 9 : 모름, 무응답
1 : 1-2잔
 2 : 3-4잔
 3 : 5-6잔
 4 : 7-9잔
 5 : 10잔 이상
 8 : 비해당
 9 : 모름
1 : 전혀 없음
 2 : 월1회미만
 3 : 월1회정도
 4 : 주1회정도
 5 : 거의 매일
 8 : 비해당
 9 : 모름
1 : 전혀 없음
 2 : 월1회미만
 3 : 월1회정도
 4 : 주1회정도
 5 : 거의 매일
 8 : 비해당
 9 : 모름
1 : 없었다
 2 : 과거에는 있었지만 최근1년동안에는 없다
 3 : 최근 1년 동안에 그런 적이 있었다
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
0 : 평생비음주
 1 : 최근 1년간 월1잔이상 음주
1 : 전혀 매지 않는다
 2 : 거의 매지 않는 편이다
 3 : 가끔 매는 편이다
 4 : 대체로 매는 편이다
 5 : 항상 맨다
 8 : 비해당
 9 : 모름, 무응답
1 : 전혀 매지 않는다
 2 : 거의 매지 않는 편이다
 3 : 가끔 매는 편이다
 4 : 대체로 매는 편이다
 5 : 항상 맨다
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 3 : 운전하지 않음
 8 : 비해당
 9 : 모름, 무응답
1 : 없음
 2 : 1번
 3 : 2-3번
 4 : 4-5번
 5 : 6번 이상
 8 : 비해당
 9 : 모름, 무응답
1 : 항상 앉음
 2 : 자주 앉음
 3 : 가끔 앉음
 4 : 거의 앉지 않음
 5 : 전혀 앉지 않음
 6 : 자동차에 타본 적이 거의 없음
 8 : 비해당
 9 : 모름, 무응답
1 : 항상 사용
 2 : 자주 사용
 3 : 가끔 사용
 4 : 거의 사용 않음
 5 : 전혀 사용 않음
 6 : 자동차에 태우지 않음
 8 : 비해당
 9 : 모름, 무응답
1 : 항상 사용
 2 : 자주 사용
 3 : 가끔 사용
 4 : 거의 사용 않음
 5 : 전혀 사용 않음
 8 : 비해당
 9 : 모름, 무응답
0 : 항상 착용하지 않음
 1 : 항상 착용
0 : 항상 착용하지 않음
 1 : 항상 착용
1 : 대단히 많이 느낀다
 2 : 많이 느끼는 편이다
 3 : 조금 느끼는 편이다
 4 : 거의 느끼지 않는다
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
1 :  예
 2 : 아니오
 8 : 비해당
 9 : 모름, 무응답
0 : 스트레스 적게 느낌
 1 : 스트레스 많이 느낌
1 : 5갑 미만
 2 : 5갑 이상
 3 : 피운적 없음
 8 : 비해당
 9 : 모름, 무응답
1 : 피움
 2 : 가끔피움
 3 : 과거엔 피웠으나, 현재 피우지 않음
 8 : 비해당
 9 : 모름, 무응답
1 : 1개월내 금연할 계획 있음
 2 : 6개월내 금연할 계획 있음
 3 : 6개월내 아니지만 언젠가 금연생각 있음
 4 : 현재 전혀 생각 없음
 8 : 비해당
 9 : 모름, 무응답
1:예
 2:아니오
 8:직장에 다니지 않음
 9:모름,무응답
1:예
 2:아니오
 8:비해당
 9:모름,무응답
1:예
 2:아니오
 3:본인을 제외한 가족 중 가정의 실내에서 일상적으로 담배를 피우는 사람 없음
 8:비해당
 9:모름,무응답
1:지금까지 없음
 2:있음
 8:비해당
 9:모름,무응답
1:현재흡연
 0: 과거 흡연, 비흡연
1: 전혀하지않음
2:1일
3:2일
4:3일
5:4일
6:5일
7:6일
8:7일(매일)
88:비해당
99:모름
1: 전혀하지않음
2:1일
3:2일
4:3일
5:4일
6:5일
7:6일
8:7일(매일)
88:비해당
99:모름
1: 전혀하지않음
2:1일
3:2일
4:3일
5:4일
6:5일
7:6일
8:7일(매일)
88:비해당
99:모름
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:매우 불편
2:불편
3:그저 그렇다
4:별로 불편하지 않음
5:전혀 불편하지 않음
9:모름
1:매우 불편
2:불편
3:그저 그렇다
4:별로 불편하지 않음
5:전혀 불편하지 않음
9:모름
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
2:아니오
9:모름
1: 경제적인 이유로
2:치과병의원이 너무 멀어서
3:직장이나 학교를 비울 수 없어서
4:거동 불편 또는 건강문제 때문에
 5: 아이를 봐줄 사람이 없어서
6:다른 문제에 비해 덜 중요하다고 느껴서
7:치과진료를 받기가 무서워서
8:기타
88:비해당
99:모름
1:매우 좋음
2:좋음
3:보통
4:나쁨
5:매우 나쁨
8: 6세 미만
1:예
2:아니오
9:모름
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1:예
0:아니오
1: 규칙적
2:불규칙적
1:오른쪽
2: 왼쪽
1: 정상
2: 고혈압전단계
3:고혈압
1: 저체중
2: 정상
3: 비만
1: 정상
2:공복혈당장애
3:당뇨병
0:없음
1:있음
0:음성
1:양성
0:없음
1:있음
0:음성
1:양성
0:음성
1:미량
2:양성
3:양성(++)
4:양성(+++)
5:양성(++++)
0:음성
1:미량
2:양성
3:양성(++)
4:양성(+++)
5:양성(++++)
0:음성
1:미량
2:양성
3:양성(++)
4:양성(+++)
5:양성(++++)
0:음성
1:미량
2:양성
3:양성(++)
4:양성(+++)
5:양성(++++)
0:음성
1:미량
2:양성
3:양성(++)
4:양성(+++)
5:양성(++++)
0:음성
1:미량
2:양성
3:양성(++)
4:양성(+++)
5:양성(++++)
1:폐기능정상
 2:제한성환기장애
 3:폐쇄성환기장애
 9:판정불능
0:우식유치 수 = 0
1:우식유치 수 >=1
0:우식영구치 수 =0
1:우식영구치 수>=1
0:우식경험유치 수=0
1:우식경험유치 수 >=1
0:우식경험유치 수=0
1:우식경험유치 수 >=1
1:하루 2회 이상
2:하루 1회
3:주1~6회
4:월1~3회
5:거의 안 한다
9:모름/무응답
1: 열량
2: 탄수화물
3:당류
4:단백질
5:지방
6:포화지방
7:트랜스지방
8:콜레스테롤
9:나트륨
10:기타
88:비해당
99:모름/무응답
1:예
2:아니오
8:비해당
9:모름/무응답
1:예
2:아니오
9:모름/무응답
1:예
2:아니오
9:모름/무응답
1: 충분한 양과 다양한 음식 먹을 수 있었다
2:충분한 양의 음식을 먹을 수 있었으나. 다양한 음식은 먹지 못했다
3:경제적으로 어려워 가끔 먹을 것 부족했다
4:경제적으로 어려워 자주 먹을 것 부족했다
9:모름/무응답
1:예
2:아니오
9:모름/무응답
1:질환이 있어서
2:체중을 조절하기 위해서
3:기타
8:비해당
9:모름/무응답

In [26]:
df_f2s.head()

,region,town_t,apt_t,sex,incm,ho_incm,incm5,ho_incm5,edu,occp,...,O_DFID,O_DMFIP,L_OUT_FQ,LK_LB_IT,LK_LB_EF,LK_EDU,LF_CARE,LF_SAFE,N_DIET,N_DIET_WHY
0,서울,동,일반,남자,중하,하,중하,하,초졸이하,NaN,...,우식경험유치 수=0,우식경험유치 수 >=1,주1~6회,비해당,비해당,아니오,아니오,충분한 양의 음식을 먹을 수 있었으나. 다양한 음식은 먹지 못했다,아니오,비해당
1,서울,동,일반,여자,중하,하,중하,하,초졸이하,"무직(주부, 학생 등)",...,우식경험유치 수=0,우식경험유치 수 >=1,주1~6회,비해당,비해당,아니오,아니오,충분한 양의 음식을 먹을 수 있었으나. 다양한 음식은 먹지 못했다,예,체중을 조절하기 위해서
2,서울,동,일반,여자,상,상,상,상,고졸,"무직(주부, 학생 등)",...,우식경험유치 수=0,우식경험유치 수=0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,서울,동,일반,여자,중상,중상,중,중상,고졸,"무직(주부, 학생 등)",...,우식경험유치 수=0,우식경험유치 수 >=1,주1~6회,열량,아니오,아니오,아니오,충분한 양과 다양한 음식 먹을 수 있었다,아니오,비해당
4,서울,동,일반,남자,중상,중상,중상,중상,초졸이하,NaN,...,우식경험유치 수=0,우식경험유치 수=0,주1~6회,비해당,비해당,예,아니오,충분한 양과 다양한 음식 먹을 수 있었다,아니오,비해당

In [27]:
f2s_dic_list

{'region': {1.0: '서울',
  2.0: '부산',
  3.0: '대구',
  4.0: '인천',
  5.0: '광주',
  6.0: '대전',
  7.0: '울산',
  8.0: '세종',
  9.0: '경기',
  10.0: '강원',
  11.0: '충북',
  12.0: '충남',
  13.0: '전북',
  14.0: '전남',
  15.0: '경북',
  16.0: '경남',
  17.0: '제주'},
 'town_t': {1.0: '동', 2.0: '읍·면'},
 'apt_t': {1.0: '일반', 2.0: '아파트'},
 'sex': {1.0: '남자', 2.0: '여자'},
 'incm': {1.0: '하', 2.0: '중하', 3.0: '중상', 4.0: '상'},
 'ho_incm': {1.0: '하', 2.0: '중하', 3.0: '중상', 4.0: '상'},
 'incm5': {1.0: '하', 2.0: '중하', 3.0: '중', 4.0: '중상', 5.0: '상'},
 'ho_incm5': {1.0: '하', 2.0: '중하', 3.0: '중', 4.0: '중상', 5.0: '상'},
 'edu': {1.0: '초졸이하', 2.0: '중졸', 3.0: '고졸', 4.0: '대졸이상'},
 'occp': {1.0: '관리자, 전문가 및 관련 종사자',
  2.0: '사무종사자',
  3.0: '서비스 및 판매 종사자',
  4.0: '농림어업 숙련 종사자',
  5.0: '기능원, 장치?기계조작 및 조립종사자',
  6.0: '단순노무종사자',
  7.0: '무직(주부, 학생 등)'},
 'cfam': {1.0: '1명',
  2.0: '2명',
  3.0: '3명',
  4.0: '4명',
  5.0: '5명',
  6.0: '6명 이상',
  9.0: '모름, 무응답'},
 'genertn': {1.0: '1세대 가구 - 1인가구',
  2.0: '1세대 가구 - 부부',
  3.0: '1세대 가구 - 기타',
  4.0: '2세대 가구 - 부부+미혼자녀',
  5.0: '2세대 가구 ? 편부모+미혼자녀',
  6.0: '2세대 가구 ? 기타',
  7.0: '3세대 이상 가구',
  9.0: '모름, 무응답'},
 'allownc': {10.0: '수급경험 있음(과거 또는 현재)', 20.0: '수급경험 없음', 99.0: '모름, 무응답'},
 'house': {1.0: '아니오', 2.0: '1채 있음', 3.0: '2채 이상 있음', 9.0: '모름, 무응답'},
 'live_t': {1.0: '단독주택',
  2.0: '아파트',
  3.0: '연립주택',
  4.0: '다세대 주택',
  5.0: '기타',
  9.0: '모름, 무응답'},
 'marri_1': {1.0: '기혼', 2.0: '미혼', 9.0: '모름, 무응답'},
 'marri_2': {1.0: '유배우자, 동거',
  2.0: '유배우자, 별거',
  3.0: '사별',
  4.0: '이혼',
  8.0: '응답거부',
  9.0: '모름',
  88.0: '비해당(문항10-E)',
  99.0: '무응답'},
 'tins': {10.0: '국민건강보험(지역)',
  20.0: '국민건강보험(직장)',
  30.0: '의료급여',
  99.0: '미가입, 모름, 무응답'},
 'npins': {1.0: '예', 2.0: '아니오', 9.0: '모름', 99.0: '무응답'},
 'D_1_1': {1.0: '매우 좋음',
  2.0: '좋음',
  3.0: '보통',
  4.0: '나쁨',
  5.0: '매우 나쁨',
  9.0: '모름, 무응답'},
 'D_2_1': {1.0: '예', 2.0: '아니오', 9.0: '모름, 무응답'},
 'DI1_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI1_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DI1_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI1_2': {1.0: '매일 복용함',
  2.0: '한달에 20일 이상 복용함',
  3.0: '한달에 15일 이상 복용함',
  4.0: '한달에 15일 미만 복용함',
  5.0: '복용하지 않음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI2_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI2_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DI2_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI2_2': {1.0: '매일 복용함',
  2.0: '한달에 20일 이상 복용함',
  3.0: '한달에 15일 이상 복용함',
  4.0: '한달에 15일 미만 복용함',
  5.0: '복용하지 않음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI3_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI3_dg': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI3_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI3_2': {1.0: '후유증을 앓고 있음',
  2.0: '후유증이 있었지만 지금은 회복되었음',
  3.0: '특별한 후유증이 없음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI4_pr': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아, 의사진단 받지 않음)'},
 'DI4_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)'},
 'DI4_pt': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아, 의사진단 받지 않음)'},
 'DI5_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI5_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DI5_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI6_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DI6_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DI6_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DM1_pr': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아, 의사진단 받지 않음)'},
 'DM1_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)'},
 'DM1_pt': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아, 의사진단 받지 않음)'},
 'DM2_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DM2_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DM2_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DM3_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DM3_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DM3_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DJ2_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DJ2_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DJ2_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DJ4_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DJ4_dg': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 지금까지 앓은 적 없음)',
  9.0: '모름, 무응답'},
 'DJ4_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DJ4_3': {1.0: '악화방지 및 천식증상관리를 위해 정기적으로 치료를 받음',
  2.0: '증상이 있을 때만 치료를 받음',
  3.0: '치료받지 않음',
  8.0: '비해당(의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DF2_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DF2_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DF2_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DL1_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DL1_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(지금까지 앓은 적 없음)', 9.0: '모름, 무응답'},
 'DL1_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DN1_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DN1_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DN1_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DE1_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DE1_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DE1_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DE1_3': {1.0: '예',
  2.0: '아니오',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DE1_31': {0.0: '아니오', 1.0: '예', 8.0: '비해당(지금까지 앓은 적 없음)', 9.0: '모름, 무응답'},
 'DE1_32': {0.0: '아니오', 1.0: '예', 8.0: '비해당(문항14-5-②⑧)', 9.0: '모름, 무응답'},
 'DE1_33': {0.0: '아니오', 1.0: '예', 8.0: '비해당(문항14-5-②⑧)', 9.0: '모름, 무응답'},
 'DE1_34': {0.0: '아니오', 1.0: '예', 8.0: '비해당(문항14-5-②⑧)', 9.0: '모름, 무응답'},
 'DE2_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DE2_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DE2_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC1_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC1_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DC1_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC2_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC2_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DC2_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC3_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC3_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DC3_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC4_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC4_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DC4_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC5_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC5_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DC5_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC6_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC6_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DC6_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC11_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DC11_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DC11_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DK8_pr': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DK8_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당(청소년, 소아)', 9.0: '모름, 무응답'},
 'DK8_pt': {0.0: '없음',
  1.0: '있음',
  8.0: '비해당(청소년, 소아, 의사진단 받지 않음)',
  9.0: '모름, 무응답'},
 'DK9_pr': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DK9_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DK9_pt': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DK4_pr': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DK4_dg': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DK4_pt': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DI9_yd': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DF1_yd': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DN6_yd': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'DJ9_yd': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'D_4_1': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH1': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH1_1': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH1_2': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH1_3': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH1_6': {0.0: '없음', 1.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH2_61': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH2_62': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH2_63': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BH2_64': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_00': {1.0: '예', 2.0: '아니오', 9.0: '모름, 무응답'},
 'LQ4_01': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_02': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_03': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_04': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_05': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_06': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_07': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_08': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_09': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_10': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_11': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_12': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_13': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_14': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_15': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_16': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_21': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_22': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_23': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_17': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_18': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_19': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ4_20': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'LQ1_sb': {1.0: '예', 2.0: '아니오', 9.0: '모름, 무응답'},
 'LQ2_ab': {1.0: '예', 2.0: '아니오', 8.0: '직장 또는 학교에 다니지 않음', 9.0: '모름, 무응답'},
 'LQ_1EQL': {1.0: '나는 걷는데 지장이 없음',
  2.0: '나는 걷는데 다소 지장이 있음',
  3.0: '나는 종일 누워 있어야 함',
  8.0: '비해당(소아청소년)',
  9.0: '모름'},
 'LQ_2EQL': {1.0: '나는 목욕을 하거나 옷을 입는데 지장이 없음',
  2.0: '나는 혼자 목욕을 하거나 옷을 입는데 다소 지장이 있음',
  3.0: '나는 혼자 목욕을 하거나 옷을 입을 수 없음',
  8.0: '비해당(소아청소년)',
  9.0: '모름'},
 'LQ_3EQL': {1.0: '나는 일상활동을 하는데 지장 없음',
  2.0: '나는 일상활동을 하는데 다소 지장 있음',
  3.0: '나는 일상활동을 할 수 없음',
  8.0: '비해당(소아청소년)',
  9.0: '모름'},
 'LQ_4EQL': {1.0: '나는 통증/불편감이 없음',
  2.0: '나는 다소 통증/불편감이 있음',
  3.0: '나는 매우 심한 통증/불편감 있음',
  8.0: '비해당(소아청소년)',
  9.0: '모름'},
 'LQ_5EQL': {1.0: '나는 불안하거나 우울하지 않음',
  2.0: '나는 다소 불안하거나 우울함',
  3.0: '나는 매우 심하게 불안하거나 우울함',
  8.0: '비해당(소아청소년)',
  9.0: '모름'},
 'educ': {1.0: '미취학',
  2.0: '서당',
  3.0: '무학',
  4.0: '초등학교',
  5.0: '중학교',
  6.0: '고등학교',
  7.0: '2/3년제 대학',
  8.0: '4년제 대학',
  9.0: '대학원',
  88.0: '소아',
  99.0: '모름'},
 'graduat': {1.0: '졸업',
  2.0: '수료',
  3.0: '중퇴',
  4.0: '재학/휴학 중',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'CH2_1': {1.0: '유치원',
  2.0: '초등학교',
  3.0: '중학교',
  4.0: '미취학',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'CH2_2': {1.0: '졸업',
  2.0: '수료',
  3.0: '중퇴',
  4.0: '재학/휴학 중',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'EC1_1': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'EC1_2': {1.0: '필요를 느끼지 못해',
  2.0: '학교/학원 재직중',
  3.0: '정년/퇴직 상태',
  4.0: '건강상의 이유',
  5.0: '실업/구직 중',
  6.0: '육아/간병',
  7.0: '기타',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'EC_stt_1': {1.0: '임금근로자',
  2.0: '자영업자와 고용주',
  3.0: '무급가족종사자',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'EC_stt_2': {1.0: '상용직', 2.0: '임시직', 3.0: '일용직', 8.0: '비해당', 9.0: '모름, 무응답'},
 'EC_wh': {1.0: '전일제', 2.0: '시간제', 8.0: '비해당', 9.0: '모름, 무응답'},
 'EC_occp': {1.0: '관리자',
  2.0: '전문가 및 관련 종사자',
  3.0: '사무종사자',
  4.0: '서비스종사자',
  5.0: '판매종사자',
  6.0: '농림어업숙련종사자',
  7.0: '기능원 및 관련기능 종사자',
  8.0: '장치, 기계조작 및 조립종사자',
  9.0: '단순노무종사자',
  10.0: '군인',
  88.0: '비해당',
  99.0: '모름'},
 'EC_lgw_2': {1.0: '관리자',
  2.0: '전문가 및 관련 종사자',
  3.0: '사무종사자',
  4.0: '서비스종사자',
  5.0: '판매종사자',
  6.0: '농림어업숙련종사자',
  7.0: '기능원 및 관련기능 종사자',
  8.0: '장치, 기계조작 및 조립종사자',
  9.0: '단순노무종사자',
  10.0: '군인',
  88.0: '비해당',
  99.0: '모름'},
 'EC_lgw_4': {1.0: '임금근로자',
  2.0: '자영업주',
  3.0: '무급가족종사자',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'EC_lgw_5': {1.0: '상용직', 2.0: '임시직', 3.0: '일용직', 8.0: '비해당', 9.0: '모름, 무응답'},
 'EC_pedu_1': {1.0: '무학',
  2.0: '서당',
  3.0: '초등학교',
  4.0: '중학교',
  5.0: '고등학교',
  6.0: '2/3년제 대학',
  7.0: '4년제 대학',
  8.0: '대학원',
  88.0: '비해당',
  99.0: '모름'},
 'EC_pedu_2': {1.0: '무학',
  2.0: '서당',
  3.0: '초등학교',
  4.0: '중학교',
  5.0: '고등학교',
  6.0: '2/3년제 대학',
  7.0: '4년제 대학',
  8.0: '대학원',
  88.0: '비해당',
  99.0: '모름'},
 'EC_wht_5': {1.0: '주간 근무',
  2.0: '저녁 근무',
  3.0: '밤 근무',
  4.0: '주야간 규칙적 교대근무',
  5.0: '24시간 교대근무',
  6.0: '분할근무',
  7.0: '불규칙 교대근무',
  8.0: '기타',
  88.0: '비해당',
  99.0: '모름'},
 'BO1': {1.0: '매우 마른 편',
  2.0: '약간 마른 편',
  3.0: '보통',
  4.0: '약간 비만',
  5.0: '매우 비만',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BO1_1': {1.0: '변화 없음',
  2.0: '체중 감소',
  3.0: '체중 증가',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BO1_2': {1.0: '3kg - 6kg 미만',
  2.0: '6kg - 10kg',
  3.0: '10kg 이상',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BO1_3': {1.0: '3kg - 6kg 미만',
  2.0: '6kg - 10kg',
  3.0: '10kg 이상',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BO2_1': {1.0: '체중 감소 노력',
  2.0: '체중 유지 노력',
  3.0: '체중 증가 노력',
  4.0: '체중 조절 노력해본 적 없음',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BO3_01': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_02': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_03': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_05': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_04': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_12': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_07': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_09': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BO3_10': {0.0: '아니오', 1.0: '예', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BD1': {1.0: '술을 마셔 본 적 없음', 2.0: '있음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BD1_11': {1.0: '최근 1년간 마시지 않음',
  2.0: '월1회미만',
  3.0: '월1회정도',
  4.0: '월2-4회',
  5.0: '주2-3회정도',
  6.0: '주4회이상',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BD2_1': {1.0: '1-2잔',
  2.0: '3-4잔',
  3.0: '5-6잔',
  4.0: '7-9잔',
  5.0: '10잔 이상',
  8.0: '비해당',
  9.0: '모름'},
 'BD2_31': {1.0: '전혀 없음',
  2.0: '월1회미만',
  3.0: '월1회정도',
  4.0: '주1회정도',
  5.0: '거의 매일',
  8.0: '비해당',
  9.0: '모름'},
 'BD2_32': {1.0: '전혀 없음',
  2.0: '월1회미만',
  3.0: '월1회정도',
  4.0: '주1회정도',
  5.0: '거의 매일',
  8.0: '비해당',
  9.0: '모름'},
 'BD7_4': {1.0: '없었다',
  2.0: '과거에는 있었지만 최근1년동안에는 없다',
  3.0: '최근 1년 동안에 그런 적이 있었다',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BD7_5': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'dr_month': {0.0: '평생비음주', 1.0: '최근 1년간 월1잔이상 음주'},
 'BA2_12': {1.0: '전혀 매지 않는다',
  2.0: '거의 매지 않는 편이다',
  3.0: '가끔 매는 편이다',
  4.0: '대체로 매는 편이다',
  5.0: '항상 맨다',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BA2_13': {1.0: '전혀 매지 않는다',
  2.0: '거의 매지 않는 편이다',
  3.0: '가끔 매는 편이다',
  4.0: '대체로 매는 편이다',
  5.0: '항상 맨다',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BA2_2_1': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BA2_2_3': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BA2_2_5': {1.0: '예', 2.0: '아니오', 3.0: '운전하지 않음', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BA2_22': {1.0: '없음',
  2.0: '1번',
  3.0: '2-3번',
  4.0: '4-5번',
  5.0: '6번 이상',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BA1_1': {1.0: '항상 앉음',
  2.0: '자주 앉음',
  3.0: '가끔 앉음',
  4.0: '거의 앉지 않음',
  5.0: '전혀 앉지 않음',
  6.0: '자동차에 타본 적이 거의 없음',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BA1_2': {1.0: '항상 사용',
  2.0: '자주 사용',
  3.0: '가끔 사용',
  4.0: '거의 사용 않음',
  5.0: '전혀 사용 않음',
  6.0: '자동차에 태우지 않음',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BA1_3': {1.0: '항상 사용',
  2.0: '자주 사용',
  3.0: '가끔 사용',
  4.0: '거의 사용 않음',
  5.0: '전혀 사용 않음',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'sc_seatblt': {0.0: '항상 착용하지 않음', 1.0: '항상 착용'},
 'sc_seatblt2': {0.0: '항상 착용하지 않음', 1.0: '항상 착용'},
 'BP1': {1.0: '대단히 많이 느낀다',
  2.0: '많이 느끼는 편이다',
  3.0: '조금 느끼는 편이다',
  4.0: '거의 느끼지 않는다',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BP5': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BP6_10': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BP6_31': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'BP7': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름, 무응답'},
 'mh_stress': {0.0: '스트레스 적게 느낌', 1.0: '스트레스 많이 느낌'},
 'BS1_1': {1.0: '5갑 미만',
  2.0: '5갑 이상',
  3.0: '피운적 없음',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BS3_1': {1.0: '피움',
  2.0: '가끔피움',
  3.0: '과거엔 피웠으나, 현재 피우지 않음',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BS5_1': {1.0: '1개월내 금연할 계획 있음',
  2.0: '6개월내 금연할 계획 있음',
  3.0: '6개월내 아니지만 언젠가 금연생각 있음',
  4.0: '현재 전혀 생각 없음',
  8.0: '비해당',
  9.0: '모름, 무응답'},
 'BS8_2': {1.0: '예', 2.0: '아니오', 8.0: '직장에 다니지 않음', 9.0: '모름,무응답'},
 'BS9_1': {1.0: '예', 2.0: '아니오', 8.0: '비해당', 9.0: '모름,무응답'},
 'BS9_2': {1.0: '예',
  2.0: '아니오',
  3.0: '본인을 제외한 가족 중 가정의 실내에서 일상적으로 담배를 피우는 사람 없음',
  8.0: '비해당',
  9.0: '모름,무응답'},
 'BS10_1': {1.0: '지금까지 없음', 2.0: '있음', 8.0: '비해당', 9.0: '모름,무응답'},
 'sm_presnt': {1.0: '현재흡연', 0.0: '과거 흡연, 비흡연'},
 'BE3_31': {1.0: '전혀하지않음',
  2.0: '1일',
  3.0: '2일',
  4.0: '3일',
  5.0: '4일',
  6.0: '5일',
  7.0: '6일',
  8.0: '7일(매일)',
  88.0: '비해당',
  99.0: '모름'},
 'BE5_2': {1.0: '전혀하지않음',
  2.0: '1일',
  3.0: '2일',
  4.0: '3일',
  5.0: '4일',
  6.0: '5일',
  7.0: '6일',
  8.0: '7일(매일)',
  88.0: '비해당',
  99.0: '모름'},
 'BE5_1': {1.0: '전혀하지않음',
  2.0: '1일',
  3.0: '2일',
  4.0: '3일',
  5.0: '4일',
  6.0: '5일',
  7.0: '6일',
  8.0: '7일(매일)',
  88.0: '비해당',
  99.0: '모름'},
 'BM1_1': {1.0: '예', 0.0: '아니오'},
 'BM1_2': {1.0: '예', 0.0: '아니오'},
 'BM1_3': {1.0: '예', 0.0: '아니오'},
 'BM1_4': {1.0: '예', 0.0: '아니오'},
 'BM1_5': {1.0: '예', 0.0: '아니오'},
 'BM1_6': {1.0: '예', 0.0: '아니오'},
 'BM1_7': {1.0: '예', 0.0: '아니오'},
 'BM1_8': {1.0: '예', 0.0: '아니오'},
 'BM7': {1.0: '매우 불편',
  2.0: '불편',
  3.0: '그저 그렇다',
  4.0: '별로 불편하지 않음',
  5.0: '전혀 불편하지 않음',
  9.0: '모름'},
 'BM8': {1.0: '매우 불편',
  2.0: '불편',
  3.0: '그저 그렇다',
  4.0: '별로 불편하지 않음',
  5.0: '전혀 불편하지 않음',
  9.0: '모름'},
 'BM2_1': {1.0: '예', 0.0: '아니오'},
 'BM2_2': {1.0: '예', 0.0: '아니오'},
 'BM2_3': {1.0: '예', 0.0: '아니오'},
 'BM2_4': {1.0: '예', 0.0: '아니오'},
 'BM2_5': {1.0: '예', 0.0: '아니오'},
 'BM12': {1.0: '예', 2.0: '아니오', 9.0: '모름'},
 'BM12_1': {1.0: '경제적인 이유로',
  2.0: '치과병의원이 너무 멀어서',
  3.0: '직장이나 학교를 비울 수 없어서',
  4.0: '거동 불편 또는 건강문제 때문에',
  5.0: '아이를 봐줄 사람이 없어서',
  6.0: '다른 문제에 비해 덜 중요하다고 느껴서',
  7.0: '치과진료를 받기가 무서워서',

In [29]:
# 모름 값(999)를 결측치로 보는 경우
df_s2f = df_f2s.copy()
s2f_dic_list= {}

for i in range(len(df_col_cat)):
        val_name = df_col_cat.iloc[i][0]
        option = df_col_cat.iloc[i][2]
        
        if option[-1] == '|':
            option = option[:-1]
        option = option.split('|')
        dic_str2float = {}
        tmp = 1.0
        
        for i in option:
            k,v = i.split(':')
            #print(v.strip()=='모름')
            #print('비해당' in v.strip())
            for s in ['비해당','다니지 않음','전혀 하지 않음']:
                if s in v.strip():
                    dic_str2float[v.strip()] = float(-1)
                    break
            for s in ['모름','응답거부','무응답','판정불능']:
                if s in v.strip():
                    dic_str2float[v.strip()] = np.nan
                    break
            if  dic_str2float.get(v.strip(),'0') == '0':
                dic_str2float[v.strip()] = tmp
                tmp += float(1)
        
        s2f_dic_list[val_name] = dic_str2float

        #dic1
        df_s2f[val_name] = df_s2f[val_name].map(dic_str2float)
        df_s2f[val_name].unique()

In [30]:
df_s2f.head()

,region,town_t,apt_t,sex,incm,ho_incm,incm5,ho_incm5,edu,occp,...,O_DFID,O_DMFIP,L_OUT_FQ,LK_LB_IT,LK_LB_EF,LK_EDU,LF_CARE,LF_SAFE,N_DIET,N_DIET_WHY
0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,...,1.0,2.0,3.0,-1.0,-1.0,2.0,2.0,2.0,2.0,-1.0
1,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,7.0,...,1.0,2.0,3.0,-1.0,-1.0,2.0,2.0,2.0,1.0,2.0
2,1.0,1.0,1.0,2.0,4.0,4.0,5.0,5.0,3.0,7.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,1.0,2.0,3.0,3.0,3.0,4.0,3.0,7.0,...,1.0,2.0,3.0,1.0,2.0,2.0,2.0,1.0,2.0,-1.0
4,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,1.0,NaN,...,1.0,1.0,3.0,-1.0,-1.0,1.0,2.0,1.0,2.0,-1.0

In [31]:
s2f_dic_list

{'region': {'서울': 1.0,
  '부산': 2.0,
  '대구': 3.0,
  '인천': 4.0,
  '광주': 5.0,
  '대전': 6.0,
  '울산': 7.0,
  '세종': 8.0,
  '경기': 9.0,
  '강원': 10.0,
  '충북': 11.0,
  '충남': 12.0,
  '전북': 13.0,
  '전남': 14.0,
  '경북': 15.0,
  '경남': 16.0,
  '제주': 17.0},
 'town_t': {'동': 1.0, '읍·면': 2.0},
 'apt_t': {'일반': 1.0, '아파트': 2.0},
 'sex': {'남자': 1.0, '여자': 2.0},
 'incm': {'하': 1.0, '중하': 2.0, '중상': 3.0, '상': 4.0},
 'ho_incm': {'하': 1.0, '중하': 2.0, '중상': 3.0, '상': 4.0},
 'incm5': {'하': 1.0, '중하': 2.0, '중': 3.0, '중상': 4.0, '상': 5.0},
 'ho_incm5': {'하': 1.0, '중하': 2.0, '중': 3.0, '중상': 4.0, '상': 5.0},
 'edu': {'초졸이하': 1.0, '중졸': 2.0, '고졸': 3.0, '대졸이상': 4.0},
 'occp': {'관리자, 전문가 및 관련 종사자': 1.0,
  '사무종사자': 2.0,
  '서비스 및 판매 종사자': 3.0,
  '농림어업 숙련 종사자': 4.0,
  '기능원, 장치?기계조작 및 조립종사자': 5.0,
  '단순노무종사자': 6.0,
  '무직(주부, 학생 등)': 7.0},
 'cfam': {'1명': 1.0,
  '2명': 2.0,
  '3명': 3.0,
  '4명': 4.0,
  '5명': 5.0,
  '6명 이상': 6.0,
  '모름, 무응답': nan},
 'genertn': {'1세대 가구 - 1인가구': 1.0,
  '1세대 가구 - 부부': 2.0,
  '1세대 가구 - 기타': 3.0,
  '2세대 가구 - 부부+미혼자녀': 4.0,
  '2세대 가구 ? 편부모+미혼자녀': 5.0,
  '2세대 가구 ? 기타': 6.0,
  '3세대 이상 가구': 7.0,
  '모름, 무응답': nan},
 'allownc': {'수급경험 있음(과거 또는 현재)': 1.0, '수급경험 없음': 2.0, '모름, 무응답': nan},
 'house': {'아니오': 1.0, '1채 있음': 2.0, '2채 이상 있음': 3.0, '모름, 무응답': nan},
 'live_t': {'단독주택': 1.0,
  '아파트': 2.0,
  '연립주택': 3.0,
  '다세대 주택': 4.0,
  '기타': 5.0,
  '모름, 무응답': nan},
 'marri_1': {'기혼': 1.0, '미혼': 2.0, '모름, 무응답': nan},
 'marri_2': {'유배우자, 동거': 1.0,
  '유배우자, 별거': 2.0,
  '사별': 3.0,
  '이혼': 4.0,
  '응답거부': nan,
  '모름': nan,
  '비해당(문항10-E)': -1.0,
  '무응답': nan},
 'tins': {'국민건강보험(지역)': 1.0,
  '국민건강보험(직장)': 2.0,
  '의료급여': 3.0,
  '미가입, 모름, 무응답': nan},
 'npins': {'예': 1.0, '아니오': 2.0, '모름': nan, '무응답': nan},
 'D_1_1': {'매우 좋음': 1.0,
  '좋음': 2.0,
  '보통': 3.0,
  '나쁨': 4.0,
  '매우 나쁨': 5.0,
  '모름, 무응답': nan},
 'D_2_1': {'예': 1.0, '아니오': 2.0, '모름, 무응답': nan},
 'DI1_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI1_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DI1_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI1_2': {'매일 복용함': 1.0,
  '한달에 20일 이상 복용함': 2.0,
  '한달에 15일 이상 복용함': 3.0,
  '한달에 15일 미만 복용함': 4.0,
  '복용하지 않음': 5.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI2_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI2_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DI2_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI2_2': {'매일 복용함': 1.0,
  '한달에 20일 이상 복용함': 2.0,
  '한달에 15일 이상 복용함': 3.0,
  '한달에 15일 미만 복용함': 4.0,
  '복용하지 않음': 5.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI3_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI3_dg': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI3_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI3_2': {'후유증을 앓고 있음': 1.0,
  '후유증이 있었지만 지금은 회복되었음': 2.0,
  '특별한 후유증이 없음': 3.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI4_pr': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0},
 'DI4_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0},
 'DI4_pt': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0},
 'DI5_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI5_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DI5_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI6_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DI6_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DI6_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DM1_pr': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0},
 'DM1_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0},
 'DM1_pt': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0},
 'DM2_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DM2_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DM2_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DM3_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DM3_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DM3_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DJ2_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DJ2_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DJ2_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DJ4_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DJ4_dg': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 지금까지 앓은 적 없음)': -1.0,
  '모름, 무응답': nan},
 'DJ4_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DJ4_3': {'악화방지 및 천식증상관리를 위해 정기적으로 치료를 받음': 1.0,
  '증상이 있을 때만 치료를 받음': 2.0,
  '치료받지 않음': 3.0,
  '비해당(의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DF2_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DF2_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DF2_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DL1_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DL1_dg': {'없음': 1.0, '있음': 2.0, '비해당(지금까지 앓은 적 없음)': -1.0, '모름, 무응답': nan},
 'DL1_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DN1_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DN1_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DN1_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DE1_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DE1_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DE1_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DE1_3': {'예': 1.0,
  '아니오': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DE1_31': {'아니오': 1.0, '예': 2.0, '비해당(지금까지 앓은 적 없음)': -1.0, '모름, 무응답': nan},
 'DE1_32': {'아니오': 1.0, '예': 2.0, '비해당(문항14-5-②⑧)': -1.0, '모름, 무응답': nan},
 'DE1_33': {'아니오': 1.0, '예': 2.0, '비해당(문항14-5-②⑧)': -1.0, '모름, 무응답': nan},
 'DE1_34': {'아니오': 1.0, '예': 2.0, '비해당(문항14-5-②⑧)': -1.0, '모름, 무응답': nan},
 'DE2_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DE2_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DE2_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC1_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC1_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DC1_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC2_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC2_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DC2_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC3_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC3_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DC3_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC4_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC4_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DC4_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC5_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC5_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DC5_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC6_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC6_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DC6_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC11_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DC11_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DC11_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DK8_pr': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DK8_dg': {'없음': 1.0, '있음': 2.0, '비해당(청소년, 소아)': -1.0, '모름, 무응답': nan},
 'DK8_pt': {'없음': 1.0,
  '있음': 2.0,
  '비해당(청소년, 소아, 의사진단 받지 않음)': -1.0,
  '모름, 무응답': nan},
 'DK9_pr': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DK9_dg': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DK9_pt': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DK4_pr': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DK4_dg': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DK4_pt': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DI9_yd': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DF1_yd': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DN6_yd': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'DJ9_yd': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'D_4_1': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH1': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH1_1': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH1_2': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH1_3': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH1_6': {'없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH2_61': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH2_62': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH2_63': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BH2_64': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_00': {'예': 1.0, '아니오': 2.0, '모름, 무응답': nan},
 'LQ4_01': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_02': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_03': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_04': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_05': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_06': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_07': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_08': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_09': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_10': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_11': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_12': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_13': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_14': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_15': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_16': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_21': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_22': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_23': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_17': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_18': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_19': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ4_20': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'LQ1_sb': {'예': 1.0, '아니오': 2.0, '모름, 무응답': nan},
 'LQ2_ab': {'예': 1.0, '아니오': 2.0, '직장 또는 학교에 다니지 않음': -1.0, '모름, 무응답': nan},
 'LQ_1EQL': {'나는 걷는데 지장이 없음': 1.0,
  '나는 걷는데 다소 지장이 있음': 2.0,
  '나는 종일 누워 있어야 함': 3.0,
  '비해당(소아청소년)': -1.0,
  '모름': nan},
 'LQ_2EQL': {'나는 목욕을 하거나 옷을 입는데 지장이 없음': 1.0,
  '나는 혼자 목욕을 하거나 옷을 입는데 다소 지장이 있음': 2.0,
  '나는 혼자 목욕을 하거나 옷을 입을 수 없음': 3.0,
  '비해당(소아청소년)': -1.0,
  '모름': nan},
 'LQ_3EQL': {'나는 일상활동을 하는데 지장 없음': 1.0,
  '나는 일상활동을 하는데 다소 지장 있음': 2.0,
  '나는 일상활동을 할 수 없음': 3.0,
  '비해당(소아청소년)': -1.0,
  '모름': nan},
 'LQ_4EQL': {'나는 통증/불편감이 없음': 1.0,
  '나는 다소 통증/불편감이 있음': 2.0,
  '나는 매우 심한 통증/불편감 있음': 3.0,
  '비해당(소아청소년)': -1.0,
  '모름': nan},
 'LQ_5EQL': {'나는 불안하거나 우울하지 않음': 1.0,
  '나는 다소 불안하거나 우울함': 2.0,
  '나는 매우 심하게 불안하거나 우울함': 3.0,
  '비해당(소아청소년)': -1.0,
  '모름': nan},
 'educ': {'미취학': 1.0,
  '서당': 2.0,
  '무학': 3.0,
  '초등학교': 4.0,
  '중학교': 5.0,
  '고등학교': 6.0,
  '2/3년제 대학': 7.0,
  '4년제 대학': 8.0,
  '대학원': 9.0,
  '소아': 10.0,
  '모름': nan},
 'graduat': {'졸업': 1.0,
  '수료': 2.0,
  '중퇴': 3.0,
  '재학/휴학 중': 4.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'CH2_1': {'유치원': 1.0,
  '초등학교': 2.0,
  '중학교': 3.0,
  '미취학': 4.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'CH2_2': {'졸업': 1.0,
  '수료': 2.0,
  '중퇴': 3.0,
  '재학/휴학 중': 4.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'EC1_1': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'EC1_2': {'필요를 느끼지 못해': 1.0,
  '학교/학원 재직중': 2.0,
  '정년/퇴직 상태': 3.0,
  '건강상의 이유': 4.0,
  '실업/구직 중': 5.0,
  '육아/간병': 6.0,
  '기타': 7.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'EC_stt_1': {'임금근로자': 1.0,
  '자영업자와 고용주': 2.0,
  '무급가족종사자': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'EC_stt_2': {'상용직': 1.0, '임시직': 2.0, '일용직': 3.0, '비해당': -1.0, '모름, 무응답': nan},
 'EC_wh': {'전일제': 1.0, '시간제': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'EC_occp': {'관리자': 1.0,
  '전문가 및 관련 종사자': 2.0,
  '사무종사자': 3.0,
  '서비스종사자': 4.0,
  '판매종사자': 5.0,
  '농림어업숙련종사자': 6.0,
  '기능원 및 관련기능 종사자': 7.0,
  '장치, 기계조작 및 조립종사자': 8.0,
  '단순노무종사자': 9.0,
  '군인': 10.0,
  '비해당': -1.0,
  '모름': nan},
 'EC_lgw_2': {'관리자': 1.0,
  '전문가 및 관련 종사자': 2.0,
  '사무종사자': 3.0,
  '서비스종사자': 4.0,
  '판매종사자': 5.0,
  '농림어업숙련종사자': 6.0,
  '기능원 및 관련기능 종사자': 7.0,
  '장치, 기계조작 및 조립종사자': 8.0,
  '단순노무종사자': 9.0,
  '군인': 10.0,
  '비해당': -1.0,
  '모름': nan},
 'EC_lgw_4': {'임금근로자': 1.0,
  '자영업주': 2.0,
  '무급가족종사자': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'EC_lgw_5': {'상용직': 1.0, '임시직': 2.0, '일용직': 3.0, '비해당': -1.0, '모름, 무응답': nan},
 'EC_pedu_1': {'무학': 1.0,
  '서당': 2.0,
  '초등학교': 3.0,
  '중학교': 4.0,
  '고등학교': 5.0,
  '2/3년제 대학': 6.0,
  '4년제 대학': 7.0,
  '대학원': 8.0,
  '비해당': -1.0,
  '모름': nan},
 'EC_pedu_2': {'무학': 1.0,
  '서당': 2.0,
  '초등학교': 3.0,
  '중학교': 4.0,
  '고등학교': 5.0,
  '2/3년제 대학': 6.0,
  '4년제 대학': 7.0,
  '대학원': 8.0,
  '비해당': -1.0,
  '모름': nan},
 'EC_wht_5': {'주간 근무': 1.0,
  '저녁 근무': 2.0,
  '밤 근무': 3.0,
  '주야간 규칙적 교대근무': 4.0,
  '24시간 교대근무': 5.0,
  '분할근무': 6.0,
  '불규칙 교대근무': 7.0,
  '기타': 8.0,
  '비해당': -1.0,
  '모름': nan},
 'BO1': {'매우 마른 편': 1.0,
  '약간 마른 편': 2.0,
  '보통': 3.0,
  '약간 비만': 4.0,
  '매우 비만': 5.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BO1_1': {'변화 없음': 1.0,
  '체중 감소': 2.0,
  '체중 증가': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BO1_2': {'3kg - 6kg 미만': 1.0,
  '6kg - 10kg': 2.0,
  '10kg 이상': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BO1_3': {'3kg - 6kg 미만': 1.0,
  '6kg - 10kg': 2.0,
  '10kg 이상': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BO2_1': {'체중 감소 노력': 1.0,
  '체중 유지 노력': 2.0,
  '체중 증가 노력': 3.0,
  '체중 조절 노력해본 적 없음': 4.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BO3_01': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_02': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_03': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_05': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_04': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_12': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_07': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_09': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BO3_10': {'아니오': 1.0, '예': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BD1': {'술을 마셔 본 적 없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BD1_11': {'최근 1년간 마시지 않음': 1.0,
  '월1회미만': 2.0,
  '월1회정도': 3.0,
  '월2-4회': 4.0,
  '주2-3회정도': 5.0,
  '주4회이상': 6.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BD2_1': {'1-2잔': 1.0,
  '3-4잔': 2.0,
  '5-6잔': 3.0,
  '7-9잔': 4.0,
  '10잔 이상': 5.0,
  '비해당': -1.0,
  '모름': nan},
 'BD2_31': {'전혀 없음': 1.0,
  '월1회미만': 2.0,
  '월1회정도': 3.0,
  '주1회정도': 4.0,
  '거의 매일': 5.0,
  '비해당': -1.0,
  '모름': nan},
 'BD2_32': {'전혀 없음': 1.0,
  '월1회미만': 2.0,
  '월1회정도': 3.0,
  '주1회정도': 4.0,
  '거의 매일': 5.0,
  '비해당': -1.0,
  '모름': nan},
 'BD7_4': {'없었다': 1.0,
  '과거에는 있었지만 최근1년동안에는 없다': 2.0,
  '최근 1년 동안에 그런 적이 있었다': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BD7_5': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'dr_month': {'평생비음주': 1.0, '최근 1년간 월1잔이상 음주': 2.0},
 'BA2_12': {'전혀 매지 않는다': 1.0,
  '거의 매지 않는 편이다': 2.0,
  '가끔 매는 편이다': 3.0,
  '대체로 매는 편이다': 4.0,
  '항상 맨다': 5.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BA2_13': {'전혀 매지 않는다': 1.0,
  '거의 매지 않는 편이다': 2.0,
  '가끔 매는 편이다': 3.0,
  '대체로 매는 편이다': 4.0,
  '항상 맨다': 5.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BA2_2_1': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BA2_2_3': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BA2_2_5': {'예': 1.0,
  '아니오': 2.0,
  '운전하지 않음': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BA2_22': {'없음': 1.0,
  '1번': 2.0,
  '2-3번': 3.0,
  '4-5번': 4.0,
  '6번 이상': 5.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BA1_1': {'항상 앉음': 1.0,
  '자주 앉음': 2.0,
  '가끔 앉음': 3.0,
  '거의 앉지 않음': 4.0,
  '전혀 앉지 않음': 5.0,
  '자동차에 타본 적이 거의 없음': 6.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BA1_2': {'항상 사용': 1.0,
  '자주 사용': 2.0,
  '가끔 사용': 3.0,
  '거의 사용 않음': 4.0,
  '전혀 사용 않음': 5.0,
  '자동차에 태우지 않음': 6.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BA1_3': {'항상 사용': 1.0,
  '자주 사용': 2.0,
  '가끔 사용': 3.0,
  '거의 사용 않음': 4.0,
  '전혀 사용 않음': 5.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'sc_seatblt': {'항상 착용하지 않음': 1.0, '항상 착용': 2.0},
 'sc_seatblt2': {'항상 착용하지 않음': 1.0, '항상 착용': 2.0},
 'BP1': {'대단히 많이 느낀다': 1.0,
  '많이 느끼는 편이다': 2.0,
  '조금 느끼는 편이다': 3.0,
  '거의 느끼지 않는다': 4.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BP5': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BP6_10': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BP6_31': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'BP7': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름, 무응답': nan},
 'mh_stress': {'스트레스 적게 느낌': 1.0, '스트레스 많이 느낌': 2.0},
 'BS1_1': {'5갑 미만': 1.0,
  '5갑 이상': 2.0,
  '피운적 없음': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BS3_1': {'피움': 1.0,
  '가끔피움': 2.0,
  '과거엔 피웠으나, 현재 피우지 않음': 3.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BS5_1': {'1개월내 금연할 계획 있음': 1.0,
  '6개월내 금연할 계획 있음': 2.0,
  '6개월내 아니지만 언젠가 금연생각 있음': 3.0,
  '현재 전혀 생각 없음': 4.0,
  '비해당': -1.0,
  '모름, 무응답': nan},
 'BS8_2': {'예': 1.0, '아니오': 2.0, '직장에 다니지 않음': -1.0, '모름,무응답': nan},
 'BS9_1': {'예': 1.0, '아니오': 2.0, '비해당': -1.0, '모름,무응답': nan},
 'BS9_2': {'예': 1.0,
  '아니오': 2.0,
  '본인을 제외한 가족 중 가정의 실내에서 일상적으로 담배를 피우는 사람 없음': 3.0,
  '비해당': -1.0,
  '모름,무응답': nan},
 'BS10_1': {'지금까지 없음': 1.0, '있음': 2.0, '비해당': -1.0, '모름,무응답': nan},
 'sm_presnt': {'현재흡연': 1.0, '과거 흡연, 비흡연': 2.0},
 'BE3_31': {'전혀하지않음': 1.0,
  '1일': 2.0,
  '2일': 3.0,
  '3일': 4.0,
  '4일': 5.0,
  '5일': 6.0,
  '6일': 7.0,
  '7일(매일)': 8.0,
  '비해당': -1.0,
  '모름': nan},
 'BE5_2': {'전혀하지않음': 1.0,
  '1일': 2.0,
  '2일': 3.0,
  '3일': 4.0,
  '4일': 5.0,
  '5일': 6.0,
  '6일': 7.0,
  '7일(매일)': 8.0,
  '비해당': -1.0,
  '모름': nan},
 'BE5_1': {'전혀하지않음': 1.0,
  '1일': 2.0,
  '2일': 3.0,
  '3일': 4.0,
  '4일': 5.0,
  '5일': 6.0,
  '6일': 7.0,
  '7일(매일)': 8.0,
  '비해당': -1.0,
  '모름': nan},
 'BM1_1': {'예': 1.0, '아니오': 2.0},
 'BM1_2': {'예': 1.0, '아니오': 2.0},
 'BM1_3': {'예': 1.0, '아니오': 2.0},
 'BM1_4': {'예': 1.0, '아니오': 2.0},
 'BM1_5': {'예': 1.0, '아니오': 2.0},
 'BM1_6': {'예': 1.0, '아니오': 2.0},
 'BM1_7': {'예': 1.0, '아니오': 2.0},
 'BM1_8': {'예': 1.0, '아니오': 2.0},
 'BM7': {'매우 불편': 1.0,
  '불편': 2.0,
  '그저 그렇다': 3.0,
  '별로 불편하지 않음': 4.0,
  '전혀 불편하지 않음': 5.0,
  '모름': nan},
 'BM8': {'매우 불편': 1.0,
  '불편': 2.0,
  '그저 그렇다': 3.0,
  '별로 불편하지 않음': 4.0,
  '전혀 불편하지 않음': 5.0,
  '모름': nan},
 'BM2_1': {'예': 1.0, '아니오': 2.0},
 'BM2_2': {'예': 1.0, '아니오': 2.0},
 'BM2_3': {'예': 1.0, '아니오': 2.0},
 'BM2_4': {'예': 1.0, '아니오': 2.0},
 'BM2_5': {'예': 1.0, '아니오': 2.0},
 'BM12': {'예': 1.0, '아니오': 2.0, '모름': nan},

In [32]:
#df = df_s2f

### 범주 + 연속형 변수

In [33]:
df_col_both = df_col_info[df_col_info['data type']=='numeric_age']
df_col_both['data type'].unique()

array(['numeric_age'], dtype=object)

In [34]:
df_col_both = df_col_both.reset_index(drop=True)
df_col_both = df_col_both.iloc[:49]      # 유아 데이터 삭제
df_col_both

,variable,variable description,option description,data type
0,age,만나이,1~79 : 1~79세 | 80 : 80세이상 |,numeric_age
1,ainc,월평균 가구총소득,17 : 월 17만원 이하 | 17초과 ~ 1500미만 : (연속형 소득금액) | ...,numeric_age
2,D_2_wk,최근2주간 불편감일수,"88 : 비해당(문항2-②) | 99 : 모름, 무응답 |",numeric_age
3,DI1_ag,고혈압 현재 유병 여부,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
4,DI2_ag,이상지질혈증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
5,DI3_ag,뇌졸중 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
6,DI5_ag,심근경색증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
7,DI6_ag,협심증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
8,DM2_ag,골관절염 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
9,DM3_ag,류마티스성 관절염 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
10,DJ2_ag,폐결핵 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
11,DJ4_ag,"천식 진단시기 (소아, 청소년 포함)",0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(의사진단 받지...,numeric_age
12,DF2_ag,우울증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
13,DL1_ag,"아토피피부염 진단시기 (소아,청소년 포함)",0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(의사진단 받지...,numeric_age
14,DN1_ag,콩팥병(신장질환) 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
15,DE1_ag,당뇨병 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
16,DE2_ag,갑상선 질환 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
17,DC1_ag,위암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
18,DC2_ag,간암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
19,DC3_ag,대장암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
20,DC4_ag,유방암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
21,DC5_ag,자궁경부암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
22,DC6_ag,폐암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
23,DC11_ag,기타암1 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
24,DK8_ag,B형간염 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
25,DK9_ag,C형간염 진단시기,1~79 : 1~79세 | 80 : 80세이상 | 888 : 비해당 | 999 :...,numeric_age
26,DK4_ag,간경변증 진단시기,1~79 : 1~79세 | 80 : 80세이상 | 888 : 비해당 | 999 :...,numeric_age
27,DI9_ya,(소아청소년) 선천성심장질환 진단연령,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
28,DF1_ya,"(청소년, 소아) 주의력결핍과잉행동장애 진단연령","888 : 비해당 | 999 : 모름, 무응답",numeric_age
29,DN6_ya,"(청소년, 소아) 요로감염 진단연령","888 : 비해당 | 999 : 모름, 무응답",numeric_age
30,DJ9_ya,"(청소년, 소아) 폐렴 진단연령","888 : 비해당 | 999 : 모름, 무응답",numeric_age
31,LQ1_mn,최근 1달간 와병일수,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
32,LQ2_mn,최근 1달간 결근일수,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
33,BD2,(만12세이상) 음주 시작 연령,1~79 : 1~79세 | 80 : 80세이상 | 888 : 비해당 | 999 :...,numeric_age
34,BA2_2_2,(성인) 1년간 음주운전 횟수: 자전거,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
35,BA2_2_4,(성인) 1년간 음주운전 횟수: 오토바이,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
36,BA2_2_6,(성인) 1년간 음주운전 횟수: 자동차,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
37,BP8,하루 평균 수면시간,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
38,BS3_2,(성인) 현재흡연자 하루평균 흡연량,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
39,BS6_2,(성인) 과거흡연자 흡연기간(월 환산),"8888 : 비해당 | 9999 : 모름, 무응답",numeric_age
40,BS6_2_1,(성인) 과거흡연자 흡연기간(연),"888:비해당 | 999:모름,무응답",numeric_age
41,BS6_2_2,(성인) 과거흡연자 흡연기간(월),"888:비해당 | 999:모름,무응답",numeric_age
42,BS6_3,(성인)과거흡연자 하루평균 흡연량,"888:비해당 | 999:모름,무응답",numeric_age
43,BS2,(청소년)1달간 하루흡연량,"888:비해당 | 999:모름,무응답",numeric_age
44,BS10_2,(청소년)1달간 흡연일수,88:비해당 | 99:모름,numeric_age
45,BS10_3,(청소년) 1달간 하루흡연량,"888: 비해당 | 999: 모름, 무응답",numeric_age
46,BE3_32,걷기 지속 시간(시간),88: 전혀 하지 않음|99:모름,numeric_age
47,BE3_33,걷기 지속 시간(분),88: 전혀 하지 않음|99:모름,numeric_age

In [35]:
age_var_ind = []          # 나이 관련 변수 인덱스
n_age_var_ind = []        # 나이와 상관 없는 변수 인덱스
for i in range(df_col_both.shape[0]):
    var_name = df_col_both.iloc[i]['variable']
    if 'ag' in var_name or 'ya' in var_name:
        age_var_ind.append(i)
    else:
        n_age_var_ind.append(i)
age_var_ind.append(34)         # 'BD2' 추가

In [36]:
df_agevar_info = df_col_both.iloc[age_var_ind].reset_index(drop=True)
df_n_agevar_info = df_col_both.iloc[n_age_var_ind].reset_index(drop=True)
# df_agevar_info

#### 나이 관련 변수 ~ 결측치 개수 확인

In [37]:
df_agevar_info

,variable,variable description,option description,data type
0,age,만나이,1~79 : 1~79세 | 80 : 80세이상 |,numeric_age
1,DI1_ag,고혈압 현재 유병 여부,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
2,DI2_ag,이상지질혈증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
3,DI3_ag,뇌졸중 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
4,DI5_ag,심근경색증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
5,DI6_ag,협심증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
6,DM2_ag,골관절염 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
7,DM3_ag,류마티스성 관절염 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
8,DJ2_ag,폐결핵 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
9,DJ4_ag,"천식 진단시기 (소아, 청소년 포함)",0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(의사진단 받지...,numeric_age
10,DF2_ag,우울증 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
11,DL1_ag,"아토피피부염 진단시기 (소아,청소년 포함)",0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(의사진단 받지...,numeric_age
12,DN1_ag,콩팥병(신장질환) 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
13,DE1_ag,당뇨병 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
14,DE2_ag,갑상선 질환 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
15,DC1_ag,위암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
16,DC2_ag,간암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
17,DC3_ag,대장암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
18,DC4_ag,유방암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
19,DC5_ag,자궁경부암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
20,DC6_ag,폐암 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
21,DC11_ag,기타암1 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
22,DK8_ag,B형간염 진단시기,"0~79 : 0~79세 | 80 : 80세이상 | 888 : 비해당(청소년, 소아...",numeric_age
23,DK9_ag,C형간염 진단시기,1~79 : 1~79세 | 80 : 80세이상 | 888 : 비해당 | 999 :...,numeric_age
24,DK4_ag,간경변증 진단시기,1~79 : 1~79세 | 80 : 80세이상 | 888 : 비해당 | 999 :...,numeric_age
25,DI9_ya,(소아청소년) 선천성심장질환 진단연령,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
26,DF1_ya,"(청소년, 소아) 주의력결핍과잉행동장애 진단연령","888 : 비해당 | 999 : 모름, 무응답",numeric_age
27,DN6_ya,"(청소년, 소아) 요로감염 진단연령","888 : 비해당 | 999 : 모름, 무응답",numeric_age
28,DJ9_ya,"(청소년, 소아) 폐렴 진단연령","888 : 비해당 | 999 : 모름, 무응답",numeric_age
29,BA2_2_2,(성인) 1년간 음주운전 횟수: 자전거,"888 : 비해당 | 999 : 모름, 무응답",numeric_age

In [38]:
agevar_list = list(df_agevar_info['variable'])

df_agevar = df[agevar_list].copy()    # df_agevar : 전체 데이터 중 나이관련 변수
df_agevar

,age,DI1_ag,DI2_ag,DI3_ag,DI5_ag,DI6_ag,DM2_ag,DM3_ag,DJ2_ag,DJ4_ag,...,DC6_ag,DC11_ag,DK8_ag,DK9_ag,DK4_ag,DI9_ya,DF1_ya,DN6_ya,DJ9_ya,BA2_2_2
0,70.0,888.0,65.0,888.0,888.0,888.0,69.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
1,68.0,888.0,64.0,888.0,888.0,888.0,60.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
2,48.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
3,35.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
4,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.0,...,NaN,NaN,NaN,NaN,NaN,888.0,888.0,888.0,888.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,10.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,2.0,888.0
39755,39.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0
39756,30.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0
39757,58.0,50.0,55.0,888.0,888.0,888.0,57.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0
39758,63.0,43.0,888.0,888.0,888.0,888.0,59.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0

In [39]:
# df_agevar['DI1_ag'].value_counts()[[888,999]].sum()
df_agevar['age'].isnull().sum()

0

In [41]:
def missing_val_count(target,col):
    if target == 'nan':
        return df_agevar[col].isnull().sum()
    else:
        return df_agevar[col].value_counts()[target].sum() if target in df_agevar[col].unique() else 0

In [42]:
missing_val_count('nan','DI1_ag')

1474

In [43]:
missing_val_count(888,'DI1_ag')

31063

In [44]:
df_agevar_mv_count = pd.DataFrame(index = list(df_agevar.columns),columns= ['nan',888,999])
for i,col in enumerate(df_agevar.columns):
    for target in ['nan',888,999]:
        df_agevar_mv_count.loc[col][target] = missing_val_count(target,col)
        #print(target)
df_agevar_mv_count

          nan    888  999
age         0      0    0
DI1_ag   1474  31063  289
DI2_ag   1474  34786  285
DI3_ag   1474  37389  278
DI5_ag   1474  37757  278
DI6_ag   1474  37457  281
DM2_ag   1474  34262  297
DM3_ag   1474  37321  282
DJ2_ag   1474  36387  286
DJ4_ag    531  37626  291
DF2_ag   1474  36651  283
DL1_ag    531  37445  296
DN1_ag   1474  37904  280
DE1_ag    531  36356  284
DE2_ag   1474  36794  287
DC1_ag   1474  37796  281
DC2_ag   1474  37975  281
DC3_ag   1474  37905  281
DC4_ag   1474  37875  281
DC5_ag   1474  37873  282
DC6_ag   1474  37974  281
DC11_ag  1481  37681  279
DK8_ag   1474  37506  284
DK9_ag   1474  37943  280
DK4_ag   1474  37919  281
DI9_ya   6500  33230    2
DF1_ya   6500  33210    1
DN6_ya   6500  33199    3
DJ9_ya   6500  32926    2
BA2_2_2  1484  36045  217

- 888을 결측치로 볼 경우 : 888값을 가지고 있는 데이터가 많아서 대부분의 데이터가 결측치로 인식되기때문에 888을 결측치로 처리하지 않음.

- 따라서 888을 결측치로 보고 삭제시킬 수 없기때문에 1번 방법(범주형 데이터 모두 삭제)는 불가능함

In [45]:
df_agevar_mv_count['ratio(nan+999)'] = (df_agevar_mv_count['nan'] + df_agevar_mv_count[999])/len(df)
df_agevar_mv_count['실제 결측치 비율'] = (df_agevar_mv_count['nan'] + df_agevar_mv_count[999])/(len(df)- df_agevar_mv_count[888])
df_agevar_mv_count

          nan    888  999 ratio(nan+999) 실제 결측치 비율
age         0      0    0            0.0       0.0
DI1_ag   1474  31063  289       0.044342  0.202737
DI2_ag   1474  34786  285       0.044242   0.35371
DI3_ag   1474  37389  278       0.044065  0.739241
DI5_ag   1474  37757  278       0.044065  0.875125
DI6_ag   1474  37457  281       0.044141  0.762381
DM2_ag   1474  34262  297       0.044543  0.322176
DM3_ag   1474  37321  282       0.044166  0.720263
DJ2_ag   1474  36387  286       0.044267  0.521945
DJ4_ag    531  37626  291       0.020675  0.385373
DF2_ag   1474  36651  283       0.044191  0.565315
DL1_ag    531  37445  296         0.0208   0.35739
DN1_ag   1474  37904  280       0.044116  0.945553
DE1_ag    531  36356  284       0.020499  0.239495
DE2_ag   1474  36794  287       0.044292  0.593929
DC1_ag   1474  37796  281       0.044141   0.89404
DC2_ag   1474  37975  281       0.044141  0.983744
DC3_ag   1474  37905  281       0.044141  0.946602
DC4_ag   1474  37875  281       0.044141  0.931529
DC5_ag   1474  37873  282       0.044166  0.931071
DC6_ag   1474  37974  281       0.044141  0.983193
DC11_ag  1481  37681  279       0.044267  0.846968
DK8_ag   1474  37506  284       0.044216  0.780293
DK9_ag   1474  37943  280       0.044116  0.965859
DK4_ag   1474  37919  281       0.044141  0.953804
DI9_ya   6500  33230    2       0.163535  0.995865
DF1_ya   6500  33210    1        0.16351  0.992671
DN6_ya   6500  33199    3        0.16356  0.991311
DJ9_ya   6500  32926    2       0.163535  0.951559
BA2_2_2  1484  36045  217       0.042783  0.457997

#### 나이 관련 변수 ~ 결측치 처리

**처리 방법**

`888` : 비해당인 카테고리로 분류
`999` : nan값으로 분류

888과 nan(999+nan) 을 제외한 연속형 변수를 나이대 별로 (10대, 20대 등)으로 범주화 한 뒤 최빈값으로 결측치를 처리함.

In [46]:
def age_category(x):
    if (x<=19):
        return 1
    elif (x>=20) and (x<=29):
        return 2
    elif (x>=30) and (x<=39):
        return 3
    elif (x>=40) and (x<=49):
        return 4
    elif (x>=50) and (x<=59):
        return 5
    elif (x>=60) and (x<=69):
        return 6
    elif (x>=70) and (x<=79):
        return 7
    elif (x>=80) and (x<888):
        return 8
#     elif x == 888:
#         return 888
#     else:
#         return 999

In [47]:
df_agevar['DI1_ag'].map(age_category).value_counts()

5.0    2192
6.0    1949
4.0    1333
7.0     781
3.0     451
2.0     120
8.0      75
1.0      32
Name: DI1_ag, dtype: int64

In [48]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

encoder_dict = {}
for col in list(df_agevar_info['variable']):
    df_agevar.loc[df_agevar[col]==999,col] = np.nan
    tmp_df = df_agevar[df_agevar[col]!=888][col]
    tmp_df = tmp_df.map(age_category).to_frame()
    freq_imputer = SimpleImputer(strategy='most_frequent')
    
    tmp_df[col] = freq_imputer.fit_transform(tmp_df[[col]])
    df_agevar.loc[df_agevar[col]!=888,col] = tmp_df[col]

    # 라벨인코더
    le = LabelEncoder()
    df_agevar[col] = le.fit_transform(df_agevar[[col]])
    encoder_dict[col] = le.classes_

In [49]:
df_agevar['DI1_ag'].value_counts()

8    31063
4     3955
5     1949
3     1333
6      781
2      451
1      120
7       75
0       32
Name: DI1_ag, dtype: int64

아래와 같은 경우라면 0 : 10대, 1 : 20대, 2 : 30대, 3 : 40대, 4 : 50대 ... 8 : 888( 비해당 )

In [50]:
encoder_dict['DI1_ag']

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8., 888.])

In [51]:
df_agevar.head()

,age,DI1_ag,DI2_ag,DI3_ag,DI5_ag,DI6_ag,DM2_ag,DM3_ag,DJ2_ag,DJ4_ag,...,DC6_ag,DC11_ag,DK8_ag,DK9_ag,DK4_ag,DI9_ya,DF1_ya,DN6_ya,DJ9_ya,BA2_2_2
0,6,8,5,8,7,8,5,8,8,8,...,5,8,7,7,6,0,0,0,0,8
1,5,8,5,8,7,8,5,8,8,8,...,5,8,7,7,6,0,0,0,0,8
2,3,8,8,8,7,8,8,8,8,8,...,5,8,7,7,6,0,0,0,0,8
3,2,8,8,8,7,8,8,8,8,8,...,5,8,7,7,6,0,0,0,0,8
4,0,4,4,5,4,5,4,4,1,8,...,2,4,1,4,2,1,1,1,1,0

#### 나이와 관련 없는 변수 ~ 결측치 개수 확인, 결측치 처리
**처리방법**


범주 + 연속형 변수 중 나이와 관련 없는 변수에서의 '비해당(88,888 등)' 은 0이라고 볼 수 있음

ex) 1달간 최근 결근 일수 라는 변수의 비해당은 결근을 한 적이 없음을 나타내며 따라서 0이라고 볼 수 있음

`888` : 0 , `999` : nan 으로 처리한다면 이 변수들은 모두 연속형 변수라고 볼 수 있다.

따라서 결측치를 중앙값으로 처리함

In [52]:
# 누락된 정보 추가
df_n_agevar_info.loc[df_n_agevar_info['variable']=='BS6_2_2','option description'] = '88:비해당 | 99:모름'
df_n_agevar_info.loc[df_n_agevar_info['variable']=='BS6_2_1','option description'] = '88:비해당 | 99:모름'
df_n_agevar_info.loc[df_n_agevar_info['variable']=='BS6_2','option description'] = '888:비해당 | 999:모름| 8888 : 비해당 | 9999 : 모름, 무응답'
df_n_agevar_info.loc[df_n_agevar_info['variable']=='BS2','option description'] = '88:비해당 | 99:모름 | 888:비해당 | 999:모름,무응답'

df_n_agevar_info

,variable,variable description,option description,data type
0,ainc,월평균 가구총소득,17 : 월 17만원 이하 | 17초과 ~ 1500미만 : (연속형 소득금액) | ...,numeric_age
1,D_2_wk,최근2주간 불편감일수,"88 : 비해당(문항2-②) | 99 : 모름, 무응답 |",numeric_age
2,LQ1_mn,최근 1달간 와병일수,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
3,LQ2_mn,최근 1달간 결근일수,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
4,BD2,(만12세이상) 음주 시작 연령,1~79 : 1~79세 | 80 : 80세이상 | 888 : 비해당 | 999 :...,numeric_age
5,BA2_2_2,(성인) 1년간 음주운전 횟수: 자전거,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
6,BA2_2_4,(성인) 1년간 음주운전 횟수: 오토바이,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
7,BA2_2_6,(성인) 1년간 음주운전 횟수: 자동차,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
8,BP8,하루 평균 수면시간,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
9,BS3_2,(성인) 현재흡연자 하루평균 흡연량,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
10,BS6_2,(성인) 과거흡연자 흡연기간(월 환산),"888:비해당 | 999:모름| 8888 : 비해당 | 9999 : 모름, 무응답",numeric_age
11,BS6_2_1,(성인) 과거흡연자 흡연기간(연),88:비해당 | 99:모름,numeric_age
12,BS6_2_2,(성인) 과거흡연자 흡연기간(월),88:비해당 | 99:모름,numeric_age
13,BS6_3,(성인)과거흡연자 하루평균 흡연량,"888:비해당 | 999:모름,무응답",numeric_age
14,BS2,(청소년)1달간 하루흡연량,"88:비해당 | 99:모름 | 888:비해당 | 999:모름,무응답",numeric_age
15,BS10_2,(청소년)1달간 흡연일수,88:비해당 | 99:모름,numeric_age
16,BS10_3,(청소년) 1달간 하루흡연량,"888: 비해당 | 999: 모름, 무응답",numeric_age
17,BE3_32,걷기 지속 시간(시간),88: 전혀 하지 않음|99:모름,numeric_age
18,BE3_33,걷기 지속 시간(분),88: 전혀 하지 않음|99:모름,numeric_age

In [53]:
df_n_agevar_info = df_n_agevar_info.drop(index = 5).reset_index(drop=True)
df_n_agevar_info

,variable,variable description,option description,data type
0,ainc,월평균 가구총소득,17 : 월 17만원 이하 | 17초과 ~ 1500미만 : (연속형 소득금액) | ...,numeric_age
1,D_2_wk,최근2주간 불편감일수,"88 : 비해당(문항2-②) | 99 : 모름, 무응답 |",numeric_age
2,LQ1_mn,최근 1달간 와병일수,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
3,LQ2_mn,최근 1달간 결근일수,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
4,BD2,(만12세이상) 음주 시작 연령,1~79 : 1~79세 | 80 : 80세이상 | 888 : 비해당 | 999 :...,numeric_age
5,BA2_2_4,(성인) 1년간 음주운전 횟수: 오토바이,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
6,BA2_2_6,(성인) 1년간 음주운전 횟수: 자동차,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
7,BP8,하루 평균 수면시간,"88 : 비해당 | 99 : 모름, 무응답",numeric_age
8,BS3_2,(성인) 현재흡연자 하루평균 흡연량,"888 : 비해당 | 999 : 모름, 무응답",numeric_age
9,BS6_2,(성인) 과거흡연자 흡연기간(월 환산),"888:비해당 | 999:모름| 8888 : 비해당 | 9999 : 모름, 무응답",numeric_age
10,BS6_2_1,(성인) 과거흡연자 흡연기간(연),88:비해당 | 99:모름,numeric_age
11,BS6_2_2,(성인) 과거흡연자 흡연기간(월),88:비해당 | 99:모름,numeric_age
12,BS6_3,(성인)과거흡연자 하루평균 흡연량,"888:비해당 | 999:모름,무응답",numeric_age
13,BS2,(청소년)1달간 하루흡연량,"88:비해당 | 99:모름 | 888:비해당 | 999:모름,무응답",numeric_age
14,BS10_2,(청소년)1달간 흡연일수,88:비해당 | 99:모름,numeric_age
15,BS10_3,(청소년) 1달간 하루흡연량,"888: 비해당 | 999: 모름, 무응답",numeric_age
16,BE3_32,걷기 지속 시간(시간),88: 전혀 하지 않음|99:모름,numeric_age
17,BE3_33,걷기 지속 시간(분),88: 전혀 하지 않음|99:모름,numeric_age

In [54]:
n_agevar_list = list(df_n_agevar_info['variable'])

df_n_agevar = df[n_agevar_list].copy()    # df_agevar : 전체 데이터 중 나이관련 변수
df_n_agevar

,ainc,D_2_wk,LQ1_mn,LQ2_mn,BD2,BA2_2_4,BA2_2_6,BP8,BS3_2,BS6_2,BS6_2_1,BS6_2_2,BS6_3,BS2,BS10_2,BS10_3,BE3_32,BE3_33
0,40.000000,88.0,88.0,88.0,14.0,888.0,888.0,9.0,10.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,1.0,0.0
1,40.000000,14.0,88.0,88.0,888.0,888.0,888.0,7.0,888.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,0.0,30.0
2,700.000000,88.0,88.0,88.0,888.0,888.0,888.0,9.0,888.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,88.0,88.0
3,333.333333,14.0,88.0,88.0,18.0,888.0,888.0,6.0,888.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,0.0,20.0
4,333.333333,88.0,88.0,88.0,888.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,88.0,88.0,888.0,0.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,666.666667,5.0,88.0,88.0,888.0,888.0,888.0,88.0,888.0,8888.0,88.0,88.0,888.0,888.0,88.0,888.0,88.0,88.0
39755,666.666667,2.0,88.0,88.0,22.0,888.0,888.0,6.0,888.0,8888.0,88.0,88.0,888.0,888.0,88.0,888.0,0.0,20.0
39756,430.000000,88.0,88.0,88.0,19.0,888.0,888.0,6.0,888.0,8888.0,88.0,88.0,888.0,888.0,88.0,888.0,1.0,30.0
39757,430.000000,7.0,88.0,88.0,20.0,888.0,888.0,6.0,888.0,180.0,15.0,0.0,20.0,888.0,88.0,888.0,4.0,0.0
39758,170.000000,88.0,88.0,88.0,43.0,888.0,888.0,6.0,888.0,8888.0,88.0,88.0,888.0,888.0,88.0,888.0,88.0,88.0

In [55]:
df_n_agevar['D_2_wk'].value_counts()[88]

30336

In [56]:
def missing_val_count_2(target,col):
    if target == 'nan':
        return df_n_agevar[col].isnull().sum()
    else:
        return df_n_agevar[col].value_counts()[target].sum() if target in df_n_agevar[col].unique() else 0

In [57]:
df_n_agevar_mv_count = pd.DataFrame(index = list(df_n_agevar.columns),columns= ['nan','비해당','모름'])
for col in df_n_agevar.columns:
    df_n_agevar_mv_count.loc[col,'nan'] = df_n_agevar[col].isnull().sum()
dict_opts = {}
for i,col in enumerate(df_n_agevar.columns):
    #print(col)
    dict_opt = {}
    for opt in df_n_agevar_info[df_n_agevar_info['variable'] == col]['option description']:
        if opt[-1] == '|':
            opt = opt[:-1]

        for j in opt.split('|'):
            j = j.strip()
            #print(col,j)
            if j.split(':')[1].strip() in ['비해당','비해당(문항2-②)','전혀 하지 않음']:
#                 print(col,j.split(':')[0])
                dict_opt['0'] = j.split(':')[1].strip()
                #print(j.split(':')[0])
                df_n_agevar_mv_count.loc[col]['비해당'] = missing_val_count_2(int(j.split(':')[0]), col)
                df_n_agevar.loc[df_n_agevar[col]==int(j.split(':')[0]),col] = 0
                
            if j.split(':')[1].strip() in ['모름, 무응답','모름','모름,무응답']:
#                 print(col,j.split(':')[0])
                dict_opt[j.split(':')[0]] = j.split(':')[1].strip()
                df_n_agevar_mv_count.loc[col]['모름'] = missing_val_count_2(int(j.split(':')[0]), col)
                df_n_agevar.loc[df_n_agevar[col]==int(j.split(':')[0]),col] = np.nan
    dict_opts[col] = dict_opt
        
    
#     for target in ['nan',888,999]:
#         df_agevar_mv_count.loc[col][target] = missing_val_count(target,col)
#         #print(target)
# df_n_agevar_mv_count

In [58]:
dict_opts['BS6_2']

{'0': '비해당', '999': '모름', '9999 ': '모름, 무응답'}

In [59]:
df_n_agevar['BS6_2'].unique()

array([  0.,  nan, 210., 240.,  72., 218., 180.,   1.,  60., 288., 300.,
        36., 444., 144., 222., 156., 480., 408., 120.,  96.,  24., 276.,
       264., 106., 216.,  32., 468., 154., 132.,  97., 420., 204., 732.,
        48., 360., 108., 372., 540., 336.,  94., 576., 130., 348.,  12.,
       123., 456., 170.,   2., 250.,  18.,  10.,   3., 138.,   6., 100.,
       324., 228., 720., 192., 564., 168., 504., 247., 242., 600., 612.,
       312.,  13., 696., 492.,  70., 362., 527.,   5.,  30., 384.,  16.,
        84., 432., 135., 134., 182., 708., 528.,  42., 792., 524.,  40.,
       744., 366.,  11., 102., 191., 173.,  99., 146.,   7., 185., 601.,
       660.,  89., 190., 396., 143., 592., 571., 214.,  76., 202., 756.,
       425., 252.,  90.,  65., 516.,  29.,  82.,  14., 186., 518., 552.,
        15.,  56., 162., 116., 166.,  85., 101., 630., 378.,  92., 315.,
       452.,  55., 305.,  41., 306.,  87., 241., 158., 217., 636., 284.,
       253., 126.,  22., 316.,  54., 245., 282., 437., 684., 648.,  17.,
       278., 370., 734., 602., 485.,  86., 438., 507.,  75., 112.,  95.,
       310., 169., 131., 128., 454., 122., 244., 503., 265., 547., 794.,
       213., 208., 149.,  62.,   8., 183.,  44.,  61.,  66., 195., 207.,
        51.,  45., 341., 374., 125., 153., 206.,  77., 221., 588.,  39.,
        79., 394., 330., 672., 768., 274.,  53., 171., 563., 311., 254.,
        43., 334., 114.,  21., 280., 246., 200.,   4.,  50., 486.,  26.,
        47., 145., 266., 307., 350., 301.,  38.,  80., 780., 150., 624.,
       117., 701., 187., 118.,  88., 580.,  33., 390., 164., 188., 141.,
       380., 424.,  63., 359., 270., 290., 556., 227.,  46., 322., 286.,
       302., 574., 111., 234.,  78., 181., 549., 189., 124.,  52., 490.,
       137.,  67., 121.,  20., 269., 371., 353., 323.,  98., 644., 233.,
       232., 422., 426., 361.,   9., 483., 338., 115., 255., 543.,  69.,
       198., 375., 402., 674., 151., 488., 174., 329., 271., 433., 236.,
       127., 386., 367., 157., 368., 159., 230., 471., 148., 661., 267.,
       365., 391., 226., 401., 481.,  34., 243., 197., 248., 140., 358.,
        71., 109.,  37.,  23.,  68.])

In [60]:
df_n_agevar['BP8'].unique()

array([ 9. ,  7. ,  6. ,  nan,  4. , 10. ,  8. ,  5. ,  3. ,  1. ,  2. ,
       11. , 12. , 15. , 14. , 13. ,  7.5,  6.5,  0. , 17. , 16. , 18. ])

In [61]:
df_n_agevar['D_2_wk'].isnull().sum()

820

In [62]:
df_n_agevar_mv_count

          nan    비해당   모름
ainc      551    NaN  NaN
D_2_wk    531  30336  289
LQ1_mn    531  35947  297
LQ2_mn    531  37549  309
BD2       795   6152  390
BA2_2_4  1484  36632  213
BA2_2_6  1484  34530  222
BP8       795    701  307
BS3_2    1484  30620  215
BS6_2    6897  21228  236
BS6_2_1  1484  31431  279
BS6_2_2  1484  31431  279
BS6_3    1484  31431  280
BS2      6754  23658    8
BS10_2   6754  32382   43
BS10_3   6754  32460  231
BE3_32    795   6186  370
BE3_33    795   6186  370

- 나이와 관련없는 변수는 비해당 값을 0으로 볼 수 있음!! 
> 그렇게 바꿀 시 연속형 변수로 들어감

In [63]:
df_n_agevar_mv_count['ratio(nan+999)'] = (df_n_agevar_mv_count['nan'] + df_n_agevar_mv_count['모름']) /len(df)
df_n_agevar_mv_count['실제 결측치 비율'] = (df_n_agevar_mv_count['nan'] + df_n_agevar_mv_count['모름'])/(len(df)- df_n_agevar_mv_count['비해당'])
df_n_agevar_mv_count['description'] = list(df_n_agevar_info['variable description'])
df_n_agevar_mv_count

          nan    비해당   모름 ratio(nan+999) 실제 결측치 비율             description
ainc      551    NaN  NaN            NaN       NaN               월평균 가구총소득
D_2_wk    531  30336  289       0.020624  0.087021             최근2주간 불편감일수
LQ1_mn    531  35947  297       0.020825  0.217209             최근 1달간 와병일수
LQ2_mn    531  37549  309       0.021127   0.38009             최근 1달간 결근일수
BD2       795   6152  390       0.029805  0.035261       (만12세이상) 음주 시작 연령
BA2_2_4  1484  36632  213       0.042682  0.542693  (성인) 1년간 음주운전 횟수: 오토바이
BA2_2_6  1484  34530  222       0.042909  0.326257   (성인) 1년간 음주운전 횟수: 자동차
BP8       795    701  307       0.027717  0.028214              하루 평균 수면시간
BS3_2    1484  30620  215       0.042732  0.185907     (성인) 현재흡연자 하루평균 흡연량
BS6_2    6897  21228  236       0.179406  0.384923   (성인) 과거흡연자 흡연기간(월 환산)
BS6_2_1  1484  31431  279       0.044342  0.211695      (성인) 과거흡연자 흡연기간(연)
BS6_2_2  1484  31431  279       0.044342  0.211695      (성인) 과거흡연자 흡연기간(월)
BS6_3    1484  31431  280       0.044367  0.211816      (성인)과거흡연자 하루평균 흡연량
BS2      6754  23658    8       0.170075  0.419974          (청소년)1달간 하루흡연량
BS10_2   6754  32382   43       0.170955  0.921377           (청소년)1달간 흡연일수
BS10_3   6754  32460  231       0.175683   0.95698         (청소년) 1달간 하루흡연량
BE3_32    795   6186  370       0.029302  0.034701            걷기 지속 시간(시간)
BE3_33    795   6186  370       0.029302  0.034701             걷기 지속 시간(분)

In [64]:
df_n_agevar

,ainc,D_2_wk,LQ1_mn,LQ2_mn,BD2,BA2_2_4,BA2_2_6,BP8,BS3_2,BS6_2,BS6_2_1,BS6_2_2,BS6_3,BS2,BS10_2,BS10_3,BE3_32,BE3_33
0,40.000000,0.0,0.0,0.0,14.0,0.0,0.0,9.0,10.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,0.0
1,40.000000,14.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,30.0
2,700.000000,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0
3,333.333333,14.0,0.0,0.0,18.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,20.0
4,333.333333,0.0,0.0,0.0,0.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,666.666667,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39755,666.666667,2.0,0.0,0.0,22.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
39756,430.000000,0.0,0.0,0.0,19.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,30.0
39757,430.000000,7.0,0.0,0.0,20.0,0.0,0.0,6.0,0.0,180.0,15.0,0.0,20.0,0.0,0.0,0.0,4.0,0.0
39758,170.000000,0.0,0.0,0.0,43.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [65]:
df_n_agevar['BS6_2'].value_counts()

0.0      26196
240.0      715
120.0      563
360.0      489
180.0      310
         ...
53.0         1
563.0        1
311.0        1
254.0        1
68.0         1
Name: BS6_2, Length: 323, dtype: int64

In [66]:
df_n_agevar

,ainc,D_2_wk,LQ1_mn,LQ2_mn,BD2,BA2_2_4,BA2_2_6,BP8,BS3_2,BS6_2,BS6_2_1,BS6_2_2,BS6_3,BS2,BS10_2,BS10_3,BE3_32,BE3_33
0,40.000000,0.0,0.0,0.0,14.0,0.0,0.0,9.0,10.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,0.0
1,40.000000,14.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,30.0
2,700.000000,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0
3,333.333333,14.0,0.0,0.0,18.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,20.0
4,333.333333,0.0,0.0,0.0,0.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,666.666667,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39755,666.666667,2.0,0.0,0.0,22.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
39756,430.000000,0.0,0.0,0.0,19.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,30.0
39757,430.000000,7.0,0.0,0.0,20.0,0.0,0.0,6.0,0.0,180.0,15.0,0.0,20.0,0.0,0.0,0.0,4.0,0.0
39758,170.000000,0.0,0.0,0.0,43.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder

for col in df_n_agevar.columns:
    median_imputer = SimpleImputer(strategy='median')
    df_n_agevar[col] = median_imputer.fit_transform(df_n_agevar[[col]])
df_n_agevar

,ainc,D_2_wk,LQ1_mn,LQ2_mn,BD2,BA2_2_4,BA2_2_6,BP8,BS3_2,BS6_2,BS6_2_1,BS6_2_2,BS6_3,BS2,BS10_2,BS10_3,BE3_32,BE3_33
0,40.000000,0.0,0.0,0.0,14.0,0.0,0.0,9.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,40.000000,14.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0
2,700.000000,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,333.333333,14.0,0.0,0.0,18.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
4,333.333333,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,666.666667,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39755,666.666667,2.0,0.0,0.0,22.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
39756,430.000000,0.0,0.0,0.0,19.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,30.0
39757,430.000000,7.0,0.0,0.0,20.0,0.0,0.0,6.0,0.0,180.0,15.0,0.0,20.0,0.0,0.0,0.0,4.0,0.0
39758,170.000000,0.0,0.0,0.0,43.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# 데이터 합치기

In [68]:
df_agevar.columns

Index(['age', 'DI1_ag', 'DI2_ag', 'DI3_ag', 'DI5_ag', 'DI6_ag', 'DM2_ag',
       'DM3_ag', 'DJ2_ag', 'DJ4_ag', 'DF2_ag', 'DL1_ag', 'DN1_ag', 'DE1_ag',
       'DE2_ag', 'DC1_ag', 'DC2_ag', 'DC3_ag', 'DC4_ag', 'DC5_ag', 'DC6_ag',
       'DC11_ag', 'DK8_ag', 'DK9_ag', 'DK4_ag', 'DI9_ya', 'DF1_ya', 'DN6_ya',
       'DJ9_ya', 'BA2_2_2'],
      dtype='object')

In [69]:
df[list(df_agevar.columns)].head()

,age,DI1_ag,DI2_ag,DI3_ag,DI5_ag,DI6_ag,DM2_ag,DM3_ag,DJ2_ag,DJ4_ag,...,DC6_ag,DC11_ag,DK8_ag,DK9_ag,DK4_ag,DI9_ya,DF1_ya,DN6_ya,DJ9_ya,BA2_2_2
0,70.0,888.0,65.0,888.0,888.0,888.0,69.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
1,68.0,888.0,64.0,888.0,888.0,888.0,60.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
2,48.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
3,35.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,888.0,...,888.0,888.0,888.0,888.0,888.0,NaN,NaN,NaN,NaN,888.0
4,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.0,...,NaN,NaN,NaN,NaN,NaN,888.0,888.0,888.0,888.0,NaN

In [70]:
df[list(df_agevar.columns)] = df_agevar
df[list(df_agevar.columns)].head()

,age,DI1_ag,DI2_ag,DI3_ag,DI5_ag,DI6_ag,DM2_ag,DM3_ag,DJ2_ag,DJ4_ag,...,DC6_ag,DC11_ag,DK8_ag,DK9_ag,DK4_ag,DI9_ya,DF1_ya,DN6_ya,DJ9_ya,BA2_2_2
0,6,8,5,8,7,8,5,8,8,8,...,5,8,7,7,6,0,0,0,0,8
1,5,8,5,8,7,8,5,8,8,8,...,5,8,7,7,6,0,0,0,0,8
2,3,8,8,8,7,8,8,8,8,8,...,5,8,7,7,6,0,0,0,0,8
3,2,8,8,8,7,8,8,8,8,8,...,5,8,7,7,6,0,0,0,0,8
4,0,4,4,5,4,5,4,4,1,8,...,2,4,1,4,2,1,1,1,1,0

In [71]:
df_n_agevar.columns

Index(['ainc', 'D_2_wk', 'LQ1_mn', 'LQ2_mn', 'BD2', 'BA2_2_4', 'BA2_2_6',
       'BP8', 'BS3_2', 'BS6_2', 'BS6_2_1', 'BS6_2_2', 'BS6_3', 'BS2', 'BS10_2',
       'BS10_3', 'BE3_32', 'BE3_33'],
      dtype='object')

In [72]:
df[list(df_n_agevar.columns)].head()

,ainc,D_2_wk,LQ1_mn,LQ2_mn,BD2,BA2_2_4,BA2_2_6,BP8,BS3_2,BS6_2,BS6_2_1,BS6_2_2,BS6_3,BS2,BS10_2,BS10_3,BE3_32,BE3_33
0,40.000000,88.0,88.0,88.0,14.0,888.0,888.0,9.0,10.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,1.0,0.0
1,40.000000,14.0,88.0,88.0,888.0,888.0,888.0,7.0,888.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,0.0,30.0
2,700.000000,88.0,88.0,88.0,888.0,888.0,888.0,9.0,888.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,88.0,88.0
3,333.333333,14.0,88.0,88.0,18.0,888.0,888.0,6.0,888.0,888.0,88.0,88.0,888.0,NaN,NaN,NaN,0.0,20.0
4,333.333333,88.0,88.0,88.0,888.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,88.0,88.0,888.0,0.0,40.0

In [73]:
df[list(df_n_agevar.columns)] = df_n_agevar
df[list(df_n_agevar.columns)].head()

,ainc,D_2_wk,LQ1_mn,LQ2_mn,BD2,BA2_2_4,BA2_2_6,BP8,BS3_2,BS6_2,BS6_2_1,BS6_2_2,BS6_3,BS2,BS10_2,BS10_3,BE3_32,BE3_33
0,40.000000,0.0,0.0,0.0,14.0,0.0,0.0,9.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,40.000000,14.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0
2,700.000000,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,333.333333,14.0,0.0,0.0,18.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
4,333.333333,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0

In [74]:
df_s2f.columns #범주형 변수 합치기

Index(['region', 'town_t', 'apt_t', 'sex', 'incm', 'ho_incm', 'incm5',
       'ho_incm5', 'edu', 'occp',
       ...
       'O_DFID', 'O_DMFIP', 'L_OUT_FQ', 'LK_LB_IT', 'LK_LB_EF', 'LK_EDU',
       'LF_CARE', 'LF_SAFE', 'N_DIET', 'N_DIET_WHY'],
      dtype='object', length=272)

In [75]:
df[list(df_s2f.columns)].head()

,region,town_t,apt_t,sex,incm,ho_incm,incm5,ho_incm5,edu,occp,...,O_DFID,O_DMFIP,L_OUT_FQ,LK_LB_IT,LK_LB_EF,LK_EDU,LF_CARE,LF_SAFE,N_DIET,N_DIET_WHY
0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,...,0.0,1.0,3.0,88.0,8.0,2.0,2.0,2.0,2.0,8.0
1,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,7.0,...,0.0,1.0,3.0,88.0,8.0,2.0,2.0,2.0,1.0,2.0
2,1.0,1.0,1.0,2.0,4.0,4.0,5.0,5.0,3.0,7.0,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,1.0,2.0,3.0,3.0,3.0,4.0,3.0,7.0,...,0.0,1.0,3.0,1.0,2.0,2.0,2.0,1.0,2.0,8.0
4,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,1.0,NaN,...,0.0,0.0,3.0,88.0,8.0,1.0,2.0,1.0,2.0,8.0

In [76]:
df[list(df_s2f.columns)] = df_s2f
df[list(df_s2f.columns)].head()

,region,town_t,apt_t,sex,incm,ho_incm,incm5,ho_incm5,edu,occp,...,O_DFID,O_DMFIP,L_OUT_FQ,LK_LB_IT,LK_LB_EF,LK_EDU,LF_CARE,LF_SAFE,N_DIET,N_DIET_WHY
0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,...,1.0,2.0,3.0,-1.0,-1.0,2.0,2.0,2.0,2.0,-1.0
1,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,7.0,...,1.0,2.0,3.0,-1.0,-1.0,2.0,2.0,2.0,1.0,2.0
2,1.0,1.0,1.0,2.0,4.0,4.0,5.0,5.0,3.0,7.0,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,1.0,2.0,3.0,3.0,3.0,4.0,3.0,7.0,...,1.0,2.0,3.0,1.0,2.0,2.0,2.0,1.0,2.0,-1.0
4,1.0,1.0,1.0,1.0,3.0,3.0,4.0,4.0,1.0,NaN,...,1.0,1.0,3.0,-1.0,-1.0,1.0,2.0,1.0,2.0,-1.0

In [77]:
lst_categorical = []

for i in df_col_info['data type'].index:
    if df_col_info['data type'][i] == 'category':
        lst_categorical.append(df_col_info['variable'][i])

In [78]:
lst_categorical

['region',
 'town_t',
 'apt_t',
 'sex',
 'incm',
 'ho_incm',
 'incm5',
 'ho_incm5',
 'edu',
 'occp',
 'cfam',
 'genertn',
 'allownc',
 'house',
 'live_t',
 'marri_1',
 'marri_2',
 'tins',
 'npins',
 'D_1_1',
 'D_2_1',
 'DI1_pr',
 'DI1_dg',
 'DI1_pt',
 'DI1_2',
 'DI2_pr',
 'DI2_dg',
 'DI2_pt',
 'DI2_2',
 'DI3_pr',
 'DI3_dg',
 'DI3_pt',
 'DI3_2',
 'DI4_pr',
 'DI4_dg',
 'DI4_pt',
 'DI5_pr',
 'DI5_dg',
 'DI5_pt',
 'DI6_pr',
 'DI6_dg',
 'DI6_pt',
 'DM1_pr',
 'DM1_dg',
 'DM1_pt',
 'DM2_pr',
 'DM2_dg',
 'DM2_pt',
 'DM3_pr',
 'DM3_dg',
 'DM3_pt',
 'DJ2_pr',
 'DJ2_dg',
 'DJ2_pt',
 'DJ4_pr',
 'DJ4_dg',
 'DJ4_pt',
 'DJ4_3',
 'DF2_pr',
 'DF2_dg',
 'DF2_pt',
 'DL1_pr',
 'DL1_dg',
 'DL1_pt',
 'DN1_pr',
 'DN1_dg',
 'DN1_pt',
 'DE1_pr',
 'DE1_dg',
 'DE1_pt',
 'DE1_3',
 'DE1_31',
 'DE1_32',
 'DE1_33',
 'DE1_34',
 'DE2_pr',
 'DE2_dg',
 'DE2_pt',
 'DC1_pr',
 'DC1_dg',
 'DC1_pt',
 'DC2_pr',
 'DC2_dg',
 'DC2_pt',
 'DC3_pr',
 'DC3_dg',
 'DC3_pt',
 'DC4_pr',
 'DC4_dg',
 'DC4_pt',
 'DC5_pr',
 'DC5_dg',
 'DC5_pt',
 'DC6_pr',
 'DC6_dg',
 'DC6_pt',
 'DC11_pr',
 'DC11_dg',
 'DC11_pt',
 'DK8_pr',
 'DK8_dg',
 'DK8_pt',
 'DK9_pr',
 'DK9_dg',
 'DK9_pt',
 'DK4_pr',
 'DK4_dg',
 'DK4_pt',
 'DI9_yd',
 'DF1_yd',
 'DN6_yd',
 'DJ9_yd',
 'D_4_1',
 'BH1',
 'BH1_1',
 'BH1_2',
 'BH1_3',
 'BH1_6',
 'BH2_61',
 'BH2_62',
 'BH2_63',
 'BH2_64',
 'LQ4_00',
 'LQ4_01',
 'LQ4_02',
 'LQ4_03',
 'LQ4_04',
 'LQ4_05',
 'LQ4_06',
 'LQ4_07',
 'LQ4_08',
 'LQ4_09',
 'LQ4_10',
 'LQ4_11',
 'LQ4_12',
 'LQ4_13',
 'LQ4_14',
 'LQ4_15',
 'LQ4_16',
 'LQ4_21',
 'LQ4_22',
 'LQ4_23',
 'LQ4_17',
 'LQ4_18',
 'LQ4_19',
 'LQ4_20',
 'LQ1_sb',
 'LQ2_ab',
 'LQ_1EQL',
 'LQ_2EQL',
 'LQ_3EQL',
 'LQ_4EQL',
 'LQ_5EQL',
 'educ',
 'graduat',
 'CH2_1',
 'CH2_2',
 'EC1_1',
 'EC1_2',
 'EC_stt_1',
 'EC_stt_2',
 'EC_wh',
 'EC_occp',
 'EC_lgw_2',
 'EC_lgw_4',
 'EC_lgw_5',
 'EC_pedu_1',
 'EC_pedu_2',
 'EC_wht_5',
 'BO1',
 'BO1_1',
 'BO1_2',
 'BO1_3',
 'BO2_1',
 'BO3_01',
 'BO3_02',
 'BO3_03',
 'BO3_05',
 'BO3_04',
 'BO3_12',
 'BO3_07',
 'BO3_09',
 'BO3_10',
 'BD1',
 'BD1_11',
 'BD2_1',
 'BD2_31',
 'BD2_32',
 'BD7_4',
 'BD7_5',
 'dr_month',
 'BA2_12',
 'BA2_13',
 'BA2_2_1',
 'BA2_2_3',
 'BA2_2_5',
 'BA2_22',
 'BA1_1',
 'BA1_2',
 'BA1_3',
 'sc_seatblt',
 'sc_seatblt2',
 'BP1',
 'BP5',
 'BP6_10',
 'BP6_31',
 'BP7',
 'mh_stress',
 'BS1_1',
 'BS3_1',
 'BS5_1',
 'BS8_2',
 'BS9_1',
 'BS9_2',
 'BS10_1',
 'sm_presnt',
 'BE3_31',
 'BE5_2',
 'BE5_1',
 'BM1_1',
 'BM1_2',
 'BM1_3',
 'BM1_4',
 'BM1_5',
 'BM1_6',
 'BM1_7',
 'BM1_8',
 'BM7',
 'BM8',
 'BM2_1',
 'BM2_2',
 'BM2_3',
 'BM2_4',
 'BM2_5',
 'BM12',
 'BM12_1',
 'OR1',
 'OR1_2',
 'HE_DMdg',
 'HE_DMdr',
 'HE_HPdg',
 'HE_HPdr',
 'HE_mens',
 'HE_prg',
 'HE_rPLS',
 'HE_nARM',
 'HE_HP',
 'HE_obe',
 'HE_DM',
 'HE_LHDL_st2',
 'HE_hepaB',
 'HE_anem',
 'HE_Unitr',
 'HE_Upro',
 'HE_Uglu',
 'HE_Uket',
 'HE_Ubil',
 'HE_Ubld',
 'HE_Uro',
 'HE_COPD',
 'O_DID',
 'O_DIP',
 'O_DFID',
 'O_DMFIP',
 'L_OUT_FQ',
 'LK_LB_IT',
 'LK_LB_EF',
 'LK_EDU',
 'LF_CARE',
 'LF_SAFE',
 'N_DIET',
 'N_DIET_WHY']

In [79]:
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder

for col in df.columns:
    #print(col)
    if col in lst_categorical:                                   # 범주형 변수 (카테고리)
        freq_imputer = SimpleImputer(strategy='most_frequent')
        df[col] = freq_imputer.fit_transform(df[[col]])
        le = LabelEncoder()
        df[col] = le.fit_transform(df[[col]])
        label_map = dict(zip(le.classes_, le.transform(le.classes_))) 
        print(col, "의 라벨링 맵 : ", label_map)
        

    else:
        if col not in agevar_list:
            #mean_imputer = SimpleImputer(strategy='mean')
            median_imputer = SimpleImputer(strategy='median')     # 중앙값
            #df[col] = mean_imputer.fit_transform(df[[col]])      # 평균
            df[col] = median_imputer.fit_transform(df[[col]])

region 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5, 7.0: 6, 8.0: 7, 9.0: 8, 10.0: 9, 11.0: 10, 12.0: 11, 13.0: 12, 14.0: 13, 15.0: 14, 16.0: 15}
town_t 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
apt_t 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
sex 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
incm 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3}
ho_incm 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3}
incm5 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
ho_incm5 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
edu 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3}
occp 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5, 7.0: 6}
cfam 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5}
genertn 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5, 7.0: 6}
allownc 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
house 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2}
live_t 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
marri_1 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
marri_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4}
tins 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2}
npins 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
D_1_1 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
D_2_1 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
DI1_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI1_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI1_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI1_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
DI2_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI2_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI2_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI2_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
DI3_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI3_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI3_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI3_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
DI4_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI4_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI4_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI5_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI5_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI5_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI6_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI6_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI6_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM1_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM1_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM1_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM2_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM2_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM2_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM3_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM3_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DM3_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ2_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ2_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ2_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ4_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ4_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ4_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ4_3 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
DF2_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DF2_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DF2_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DL1_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DL1_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DL1_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DN1_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DN1_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DN1_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_3 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_31 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_32 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_33 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE1_34 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE2_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE2_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DE2_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC1_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC1_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC1_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC2_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC2_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC2_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC3_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC3_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC3_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC4_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC4_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC4_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC5_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC5_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC5_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC6_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC6_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC6_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC11_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC11_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DC11_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK8_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK8_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK8_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK9_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK9_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK9_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK4_pr 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK4_dg 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DK4_pt 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DI9_yd 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DF1_yd 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DN6_yd 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
DJ9_yd 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
D_4_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BH1 의 라벨링 맵 :  {-1.0: 0, 2.0: 1}
BH1_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BH1_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BH1_3 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BH1_6 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BH2_61 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BH2_62 의 라벨링 맵 :  {-1.0: 0, 1.0: 1}
BH2_63 의 라벨링 맵 :  {-1.0: 0, 1.0: 1}
BH2_64 의 라벨링 맵 :  {-1.0: 0, 1.0: 1}
LQ4_00 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
LQ4_01 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_02 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_03 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_04 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_05 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_06 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_07 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_08 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_09 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_10 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_11 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_12 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_13 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_14 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_15 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_16 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_21 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_22 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_23 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_17 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_18 의 라벨링 맵 :  {-1.0: 0, 1.0: 1}
LQ4_19 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ4_20 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ1_sb 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
LQ2_ab 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LQ_1EQL 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
LQ_2EQL 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
LQ_3EQL 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
LQ_4EQL 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
LQ_5EQL 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
educ 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5, 7.0: 6, 8.0: 7, 9.0: 8, 10.0: 9}
graduat 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4}
CH2_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 4.0: 3}
CH2_2 의 라벨링 맵 :  {-1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3}
EC1_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
EC1_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7}
EC_stt_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
EC_stt_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
EC_wh 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
EC_occp 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8, 9.0: 9, 10.0: 10}
EC_lgw_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8, 9.0: 9, 10.0: 10}
EC_lgw_4 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
EC_lgw_5 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
EC_pedu_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8}
EC_pedu_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8}
EC_wht_5 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8}
BO1 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
BO1_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BO1_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BO1_3 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BO2_1 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3}
BO3_01 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_02 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_03 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_05 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_04 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_12 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_07 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_09 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BO3_10 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BD1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BD1_11 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6}
BD2_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
BD2_31 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
BD2_32 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
BD7_4 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BD7_5 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
dr_month 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BA2_12 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
BA2_13 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
BA2_2_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BA2_2_3 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BA2_2_5 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BA2_22 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
BA1_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6}
BA1_2 의 라벨링 맵 :  {-1.0: 0}
BA1_3 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5}
sc_seatblt 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
sc_seatblt2 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BP1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4}
BP5 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BP6_10 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BP6_31 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BP7 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
mh_stress 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BS1_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BS3_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BS5_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4}
BS8_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BS9_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
BS9_2 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}
BS10_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
sm_presnt 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BE3_31 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8}
BE5_2 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5, 8.0: 6}
BE5_1 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5, 8.0: 6}
BM1_1 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM1_2 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM1_3 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM1_4 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM1_5 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM1_6 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM1_7 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM1_8 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM7 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
BM8 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
BM2_1 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM2_2 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM2_3 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM2_4 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM2_5 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
BM12 의 라벨링 맵 :  {1.0: 0}
BM12_1 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8}
OR1 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
OR1_2 의 라벨링 맵 :  {1.0: 0}
HE_DMdg 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_DMdr 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_HPdg 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_HPdr 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_mens 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_prg 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_rPLS 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_nARM 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_HP 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2}
HE_obe 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2}
HE_DM 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2}
HE_LHDL_st2 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_hepaB 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_anem 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_Unitr 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
HE_Upro 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
HE_Uglu 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
HE_Uket 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
HE_Ubil 의 라벨링 맵 :  {1.0: 0, 3.0: 1, 4.0: 2, 5.0: 3}
HE_Ubld 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4, 6.0: 5}
HE_Uro 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
HE_COPD 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2}
O_DID 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
O_DIP 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
O_DFID 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
O_DMFIP 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
L_OUT_FQ 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3, 5.0: 4}
LK_LB_IT 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3, 4.0: 4, 5.0: 5, 6.0: 6, 7.0: 7, 8.0: 8, 9.0: 9, 10.0: 10}
LK_LB_EF 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2}
LK_EDU 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
LF_CARE 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
LF_SAFE 의 라벨링 맵 :  {1.0: 0, 2.0: 1, 3.0: 2, 4.0: 3}
N_DIET 의 라벨링 맵 :  {1.0: 0, 2.0: 1}
N_DIET_WHY 의 라벨링 맵 :  {-1.0: 0, 1.0: 1, 2.0: 2, 3.0: 3}

In [80]:
df

,year,region,town_t,apt_t,sex,age,incm,ho_incm,incm5,ho_incm5,...,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC,HE_vitD
0,2008.0,0,0,0,0,6,1,0,1,0,...,7472.249217,4895.631231,881.735572,5273.157673,2.203960,1.561326,0.987078,16.272761,262.812776,14.85
1,2008.0,0,0,0,1,5,1,0,1,0,...,4430.090787,3680.878220,777.813158,4646.511191,2.188609,1.116872,0.729980,11.567262,206.477449,14.05
2,2008.0,0,0,0,1,3,3,3,4,4,...,3928.688345,2684.283446,568.489544,2778.926550,57.433192,1.179597,1.072590,14.152700,78.229656,10.36
3,2008.0,0,0,0,1,2,2,2,2,3,...,2684.503728,3310.676976,1932.710046,10725.673284,144.044389,0.909731,1.101102,9.129266,147.954071,18.52
4,2008.0,0,0,0,0,0,2,2,3,3,...,2796.580638,2984.102868,434.816014,571.273052,166.161773,1.212672,1.752693,8.201845,65.331394,18.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,2014.0,15,0,1,0,0,3,3,4,4,...,3928.688345,2684.283446,568.489544,2778.926550,57.433192,1.179597,1.072590,14.152700,78.229656,22.04
39755,2014.0,15,0,1,1,2,3,3,4,4,...,3685.879396,1880.994894,1933.891026,1906.202132,1615.497101,2.497810,1.278473,14.143210,36.145233,16.25
39756,2014.0,15,0,1,0,2,2,2,2,3,...,2043.568097,1147.876072,300.249632,1793.774635,0.983537,0.791706,0.511638,6.020183,27.892272,18.58
39757,2014.0,15,0,1,0,4,2,2,2,3,...,1758.339159,1446.924818,189.142622,1124.184551,1.043302,1.490047,0.384598,8.750881,24.329294,20.63
39758,2014.0,15,0,1,1,5,1,1,2,1,...,4135.396263,3929.953846,1128.278822,6215.580482,90.872025,2.617619,1.530583,13.680425,126.004317,15.74

In [81]:
df_no_scailing = df.copy() # 정규화 전 데이터 저장 (시각화 위해서)
df_no_scailing

,year,region,town_t,apt_t,sex,age,incm,ho_incm,incm5,ho_incm5,...,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC,HE_vitD
0,2008.0,0,0,0,0,6,1,0,1,0,...,7472.249217,4895.631231,881.735572,5273.157673,2.203960,1.561326,0.987078,16.272761,262.812776,14.85
1,2008.0,0,0,0,1,5,1,0,1,0,...,4430.090787,3680.878220,777.813158,4646.511191,2.188609,1.116872,0.729980,11.567262,206.477449,14.05
2,2008.0,0,0,0,1,3,3,3,4,4,...,3928.688345,2684.283446,568.489544,2778.926550,57.433192,1.179597,1.072590,14.152700,78.229656,10.36
3,2008.0,0,0,0,1,2,2,2,2,3,...,2684.503728,3310.676976,1932.710046,10725.673284,144.044389,0.909731,1.101102,9.129266,147.954071,18.52
4,2008.0,0,0,0,0,0,2,2,3,3,...,2796.580638,2984.102868,434.816014,571.273052,166.161773,1.212672,1.752693,8.201845,65.331394,18.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,2014.0,15,0,1,0,0,3,3,4,4,...,3928.688345,2684.283446,568.489544,2778.926550,57.433192,1.179597,1.072590,14.152700,78.229656,22.04
39755,2014.0,15,0,1,1,2,3,3,4,4,...,3685.879396,1880.994894,1933.891026,1906.202132,1615.497101,2.497810,1.278473,14.143210,36.145233,16.25
39756,2014.0,15,0,1,0,2,2,2,2,3,...,2043.568097,1147.876072,300.249632,1793.774635,0.983537,0.791706,0.511638,6.020183,27.892272,18.58
39757,2014.0,15,0,1,0,4,2,2,2,3,...,1758.339159,1446.924818,189.142622,1124.184551,1.043302,1.490047,0.384598,8.750881,24.329294,20.63
39758,2014.0,15,0,1,1,5,1,1,2,1,...,4135.396263,3929.953846,1128.278822,6215.580482,90.872025,2.617619,1.530583,13.680425,126.004317,15.74

In [82]:
df_no_scailing['EC_occp'].unique()

array([ 0,  9,  2,  7,  5,  8,  4,  3,  6,  1, 10])

In [83]:
le.classes_

array([-1.,  1.,  2.,  3.])

## 정규화

In [84]:
numeric_var = list(df_col_info[df_col_info['data type'] == 'numeric']['variable']) + n_agevar_list # 연속형 변수로 보는거 다시처리
len(numeric_var)

76

In [85]:
df[numeric_var]

,year,EQ5D,HE_fst,HE_dprg,HE_PLS,HE_mPLS,HE_sbp1,HE_dbp1,HE_sbp2,HE_dbp2,...,BS3_2,BS6_2,BS6_2_1,BS6_2_2,BS6_3,BS2,BS10_2,BS10_3,BE3_32,BE3_33
0,2008.0,0.817,3.0,5.0,17.0,56.0,128.0,76.0,122.0,70.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2008.0,0.723,16.0,5.0,15.0,56.0,138.0,88.0,128.0,84.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0
2,2008.0,1.000,16.0,5.0,21.0,56.0,140.0,96.0,134.0,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2008.0,1.000,14.0,5.0,13.0,56.0,106.0,72.0,108.0,72.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
4,2008.0,1.000,15.0,5.0,19.0,56.0,84.0,40.0,90.0,50.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,2014.0,1.000,13.0,5.0,20.0,56.0,100.0,76.0,94.0,68.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39755,2014.0,1.000,13.0,5.0,18.0,56.0,110.0,74.0,110.0,72.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
39756,2014.0,1.000,11.0,5.0,17.0,56.0,132.0,98.0,130.0,94.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,30.0
39757,2014.0,1.000,14.0,5.0,16.0,56.0,148.0,100.0,150.0,102.0,...,0.0,180.0,15.0,0.0,20.0,0.0,0.0,0.0,4.0,0.0
39758,2014.0,1.000,13.0,5.0,16.0,56.0,150.0,92.0,142.0,92.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
from sklearn.preprocessing import StandardScaler

# 예시 데이터 생성
# data = pd.DataFrame({'x1': [1, 2, 3, 4], 'x2': [100, 200, 300, 400]})

# StandardScaler 객체 생성
scaler = StandardScaler()

# 각 열에 대해 StandardScaler 객체 생성
scalers = {col: StandardScaler() for col in numeric_var}

# 각 열에 대해 스케일링 수행
data_scaled = pd.DataFrame({col: scalers[col].fit_transform(df[[col]])[:,0] for col in numeric_var})

# 스케일링된 데이터를 데이터프레임으로 변환
df[numeric_var] = data_scaled


# 결과 확인
df

,year,region,town_t,apt_t,sex,age,incm,ho_incm,incm5,ho_incm5,...,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC,HE_vitD
0,-1.337160,0,0,0,0,6,1,0,1,0,...,1.012888,1.321272,0.096310,0.222994,-0.310686,0.252820,-0.287877,0.038525,1.704659,14.85
1,-1.337160,0,0,0,1,5,1,0,1,0,...,-0.037454,0.501629,-0.003061,0.115658,-0.310734,-0.294634,-0.641509,-0.497944,1.107824,14.05
2,-1.337160,0,0,0,1,3,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,10.36
3,-1.337160,0,0,0,1,2,2,2,2,3,...,-0.640139,0.251839,1.101258,1.156936,0.129821,-0.549778,-0.131039,-0.775898,0.487808,18.52
4,-1.337160,0,0,0,0,0,2,2,3,3,...,-0.601443,0.031486,-0.331037,-0.582375,0.198510,-0.176632,0.765210,-0.881632,-0.387523,18.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,2.087408,15,0,1,0,0,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,22.04
39755,2.087408,15,0,1,1,2,3,3,4,4,...,-0.294402,-0.712826,1.102388,-0.353720,4.699642,1.406329,0.112931,-0.204263,-0.696731,16.25
39756,2.087408,15,0,1,0,2,2,2,2,3,...,-0.861430,-1.207491,-0.459710,-0.372977,-0.314476,-0.695156,-0.941833,-1.130361,-0.784165,18.58
39757,2.087408,15,0,1,0,4,2,2,2,3,...,-0.959909,-1.005711,-0.565952,-0.487669,-0.314291,0.165022,-1.116573,-0.819037,-0.821913,20.63
39758,2.087408,15,0,1,1,5,1,1,2,1,...,-0.139201,0.669690,0.332056,0.384418,-0.035314,1.553903,0.459702,-0.257025,0.255266,15.74

# 비타민 D 범주화

- 결핍상태: 혈중 25(OH)D3 농도 < 12ng/ml
- 불충분상태: 12ng/ml <= 혈중 25(OH)D3 농도 <= 19.9ng/ml
- 충분상태: 20 <= 혈중 25(OH)D3 농도

In [87]:
def vitD2categorical(value):
    '''
    비타민 D 범주화
    
    args
        value: 비타민 D 혈중 농도
        
    return
        target: '결핍' or '불충분' or '충분'
    '''
    if value < 12:
        return '결핍'
    
    elif (value >= 12) & (value < 20):
        return '불충분'
    
    elif value >= 20:
        return '충분'

In [88]:
df['HE_vitD'] = df['HE_vitD'].map(vitD2categorical)
df_no_scailing['HE_vitD'] = df_no_scailing['HE_vitD'].map(vitD2categorical)

In [89]:
df

,year,region,town_t,apt_t,sex,age,incm,ho_incm,incm5,ho_incm5,...,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC,HE_vitD
0,-1.337160,0,0,0,0,6,1,0,1,0,...,1.012888,1.321272,0.096310,0.222994,-0.310686,0.252820,-0.287877,0.038525,1.704659,불충분
1,-1.337160,0,0,0,1,5,1,0,1,0,...,-0.037454,0.501629,-0.003061,0.115658,-0.310734,-0.294634,-0.641509,-0.497944,1.107824,불충분
2,-1.337160,0,0,0,1,3,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,결핍
3,-1.337160,0,0,0,1,2,2,2,2,3,...,-0.640139,0.251839,1.101258,1.156936,0.129821,-0.549778,-0.131039,-0.775898,0.487808,불충분
4,-1.337160,0,0,0,0,0,2,2,3,3,...,-0.601443,0.031486,-0.331037,-0.582375,0.198510,-0.176632,0.765210,-0.881632,-0.387523,불충분
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,2.087408,15,0,1,0,0,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,충분
39755,2.087408,15,0,1,1,2,3,3,4,4,...,-0.294402,-0.712826,1.102388,-0.353720,4.699642,1.406329,0.112931,-0.204263,-0.696731,불충분
39756,2.087408,15,0,1,0,2,2,2,2,3,...,-0.861430,-1.207491,-0.459710,-0.372977,-0.314476,-0.695156,-0.941833,-1.130361,-0.784165,불충분
39757,2.087408,15,0,1,0,4,2,2,2,3,...,-0.959909,-1.005711,-0.565952,-0.487669,-0.314291,0.165022,-1.116573,-0.819037,-0.821913,충분
39758,2.087408,15,0,1,1,5,1,1,2,1,...,-0.139201,0.669690,0.332056,0.384418,-0.035314,1.553903,0.459702,-0.257025,0.255266,불충분

## target 설정

In [90]:
def target(df, by='analysis1'):
    '''
    비타민 D 범주화
    
    args
        df: pd.DataFrame()
        by: {'analysis1', 'analysis2'}, default='analysis1'
        
    return
        result: pd.DataFrame()
    '''
    
    result = df.copy()
    
    if by == 'analysis1':
        dic_str2categorical = {'결핍': 1, '불충분': 0, '충분': 0}
        result['HE_vitD'] = result['HE_vitD'].map(dic_str2categorical)
        
    elif by == 'analysis2':
        dic_str2categorical = {'결핍': 1, '불충분': 1, '충분': 0}
        result['HE_vitD'] = result['HE_vitD'].map(dic_str2categorical)
        
    return result

In [91]:
df_anal1 = target(df, by='analysis1')
df_anal2 = target(df, by='analysis2')

df_no_scailing_1 = target(df_no_scailing, by='analysis1')
df_no_scailing_2 = target(df_no_scailing, by='analysis2')

In [92]:
df_anal1

,year,region,town_t,apt_t,sex,age,incm,ho_incm,incm5,ho_incm5,...,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC,HE_vitD
0,-1.337160,0,0,0,0,6,1,0,1,0,...,1.012888,1.321272,0.096310,0.222994,-0.310686,0.252820,-0.287877,0.038525,1.704659,0
1,-1.337160,0,0,0,1,5,1,0,1,0,...,-0.037454,0.501629,-0.003061,0.115658,-0.310734,-0.294634,-0.641509,-0.497944,1.107824,0
2,-1.337160,0,0,0,1,3,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,1
3,-1.337160,0,0,0,1,2,2,2,2,3,...,-0.640139,0.251839,1.101258,1.156936,0.129821,-0.549778,-0.131039,-0.775898,0.487808,0
4,-1.337160,0,0,0,0,0,2,2,3,3,...,-0.601443,0.031486,-0.331037,-0.582375,0.198510,-0.176632,0.765210,-0.881632,-0.387523,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,2.087408,15,0,1,0,0,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,0
39755,2.087408,15,0,1,1,2,3,3,4,4,...,-0.294402,-0.712826,1.102388,-0.353720,4.699642,1.406329,0.112931,-0.204263,-0.696731,0
39756,2.087408,15,0,1,0,2,2,2,2,3,...,-0.861430,-1.207491,-0.459710,-0.372977,-0.314476,-0.695156,-0.941833,-1.130361,-0.784165,0
39757,2.087408,15,0,1,0,4,2,2,2,3,...,-0.959909,-1.005711,-0.565952,-0.487669,-0.314291,0.165022,-1.116573,-0.819037,-0.821913,0
39758,2.087408,15,0,1,1,5,1,1,2,1,...,-0.139201,0.669690,0.332056,0.384418,-0.035314,1.553903,0.459702,-0.257025,0.255266,0

In [93]:
df_anal2

,year,region,town_t,apt_t,sex,age,incm,ho_incm,incm5,ho_incm5,...,N_NA,N_K,N_VA,N_CAROT,N_RETIN,N_B1,N_B2,N_NIAC,N_VITC,HE_vitD
0,-1.337160,0,0,0,0,6,1,0,1,0,...,1.012888,1.321272,0.096310,0.222994,-0.310686,0.252820,-0.287877,0.038525,1.704659,1
1,-1.337160,0,0,0,1,5,1,0,1,0,...,-0.037454,0.501629,-0.003061,0.115658,-0.310734,-0.294634,-0.641509,-0.497944,1.107824,1
2,-1.337160,0,0,0,1,3,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,1
3,-1.337160,0,0,0,1,2,2,2,2,3,...,-0.640139,0.251839,1.101258,1.156936,0.129821,-0.549778,-0.131039,-0.775898,0.487808,1
4,-1.337160,0,0,0,0,0,2,2,3,3,...,-0.601443,0.031486,-0.331037,-0.582375,0.198510,-0.176632,0.765210,-0.881632,-0.387523,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,2.087408,15,0,1,0,0,3,3,4,4,...,-0.210569,-0.170814,-0.203218,-0.204234,-0.139163,-0.217373,-0.170257,-0.203181,-0.250875,0
39755,2.087408,15,0,1,1,2,3,3,4,4,...,-0.294402,-0.712826,1.102388,-0.353720,4.699642,1.406329,0.112931,-0.204263,-0.696731,1
39756,2.087408,15,0,1,0,2,2,2,2,3,...,-0.861430,-1.207491,-0.459710,-0.372977,-0.314476,-0.695156,-0.941833,-1.130361,-0.784165,1
39757,2.087408,15,0,1,0,4,2,2,2,3,...,-0.959909,-1.005711,-0.565952,-0.487669,-0.314291,0.165022,-1.116573,-0.819037,-0.821913,0
39758,2.087408,15,0,1,1,5,1,1,2,1,...,-0.139201,0.669690,0.332056,0.384418,-0.035314,1.553903,0.459702,-0.257025,0.255266,1

# Training

In [94]:
def train(dic, X, y, num=1):
    '''
    모델 학습
    
    args
        dic: dictionary
        X: explanatory variable
        y: target variable
        num: {1, 2}, default=1
        
    return
        pickle file
    '''
    
    for name in dic.keys():
        print('model: {}'.format(name))
        
        clf = dic[name]
        clf.fit(X, y)
        
        with open('clf_{}_anal{}_ver1.pickle'.format(name, num), 'wb') as f:
            pickle.dump(clf, f)

In [95]:
clf_rf = RandomForestClassifier(n_estimators=1000, random_state=42,n_jobs = 30)
clf_gb = GradientBoostingClassifier(n_estimators=1000, random_state=42)
clf_xgb = XGBClassifier(n_estimators=1000, random_state=42,n_jobs = 30)
clf_lgb = LGBMClassifier(n_estimators=1000, random_state=42,n_jobs = 30)
clf_cb = CatBoostClassifier(random_state=42,cat_features = lst_categorical)

In [96]:
dic_name2model = {'rf': clf_rf, 'gb': clf_gb, 'xgb': clf_xgb, 'lgb': clf_lgb, 'cb': clf_cb}

## analysis 2

In [97]:
X2 = df_anal2.iloc[:,:-1]
y2 = df_anal2.iloc[:,-1]

In [98]:
train(dic=dic_name2model, num=2, X=X2, y=y2)

model: rf
model: gb
model: xgb
[19:29:42] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
model: lgb
model: cb
Learning rate set to 0.049647
0:	learn: 0.6819588	total: 501ms	remaining: 8m 20s
1:	learn: 0.6720567	total: 963ms	remaining: 8m
2:	learn: 0.6632527	total: 1.36s	remaining: 7m 33s
3:	learn: 0.6553019	total: 1.76s	remaining: 7m 18s
4:	learn: 0.6478357	total: 2.25s	remaining: 7m 27s
5:	learn: 0.6415624	total: 2.66s	remaining: 7m 20s
6:	learn: 0.6358422	total: 2.98s	remaining: 7m 3s
7:	learn: 0.6303656	total: 3.39s	remaining: 7m
8:	learn: 0.6253644	total: 3.8s	remaining: 6m 58s
9:	learn: 0.6205023	total: 4.14s	remaining: 6m 49s
10:	learn: 0.6166215	total: 4.54s	remaining: 6m 48s
11:	learn: 0.6127142	total: 4.95s	remaining: 6m 47s
12:	learn: 0.6095351	total: 5.36s	remaining: 6m 47s
13:	learn: 0.6063972	total: 5.78s	remaining: 6m 46s
14:	learn: 0.6037688	total: 6.19s	remaining: 6m 46s
15:	learn: 0.6011709	total: 6.6s	remaining: 6m 45s
16:	learn: 0.5983827	total: 7.01s	remaining: 6m 45s
17:	learn: 0.5959338	total: 7.42s	remaining: 6m 44s
18:	learn: 0.5935890	total: 7.83s	remaining: 6m 44s
19:	learn: 0.5917409	total: 8.23s	remaining: 6m 43s
20:	learn: 0.5900181	total: 8.65s	remaining: 6m 43s
21:	learn: 0.5884868	total: 8.99s	remaining: 6m 39s
22:	learn: 0.5868405	total: 9.4s	remaining: 6m 39s
23:	learn: 0.5853840	total: 9.81s	remaining: 6m 38s
24:	learn: 0.5839818	total: 10.2s	remaining: 6m 38s
25:	learn: 0.5824882	total: 10.6s	remaining: 6m 38s
26:	learn: 0.5813732	total: 11s	remaining: 6m 37s
27:	learn: 0.5802652	total: 11.5s	remaining: 6m 37s
28:	learn: 0.5793248	total: 11.9s	remaining: 6m 37s
29:	learn: 0.5782364	total: 12.3s	remaining: 6m 36s
30:	learn: 0.5770426	total: 12.7s	remaining: 6m 36s
31:	learn: 0.5759708	total: 13.1s	remaining: 6m 36s
32:	learn: 0.5749568	total: 13.5s	remaining: 6m 35s
33:	learn: 0.5739719	total: 13.9s	remaining: 6m 35s
34:	learn: 0.5732437	total: 14.3s	remaining: 6m 34s
35:	learn: 0.5725878	total: 14.7s	remaining: 6m 34s
36:	learn: 0.5719976	total: 15.1s	remaining: 6m 34s
37:	learn: 0.5714698	total: 15.6s	remaining: 6m 33s
38:	learn: 0.5708430	total: 16s	remaining: 6m 33s
39:	learn: 0.5702387	total: 16.4s	remaining: 6m 32s
40:	learn: 0.5696900	total: 16.8s	remaining: 6m 32s
41:	learn: 0.5693560	total: 17s	remaining: 6m 28s
42:	learn: 0.5688735	total: 17.4s	remaining: 6m 27s
43:	learn: 0.5683146	total: 17.8s	remaining: 6m 26s
44:	learn: 0.5677259	total: 18.1s	remaining: 6m 24s
45:	learn: 0.5673087	total: 18.5s	remaining: 6m 24s
46:	learn: 0.5669028	total: 18.9s	remaining: 6m 24s
47:	learn: 0.5664610	total: 19.4s	remaining: 6m 23s
48:	learn: 0.5660730	total: 19.8s	remaining: 6m 23s
49:	learn: 0.5659124	total: 19.9s	remaining: 6m 18s
50:	learn: 0.5654647	total: 20.3s	remaining: 6m 18s
51:	learn: 0.5650780	total: 20.8s	remaining: 6m 18s
52:	learn: 0.5647736	total: 21.2s	remaining: 6m 18s
53:	learn: 0.5643344	total: 21.6s	remaining: 6m 17s
54:	learn: 0.5639059	total: 22s	remaining: 6m 17s
55:	learn: 0.5636101	total: 22.4s	remaining: 6m 17s
56:	learn: 0.5633635	total: 22.8s	remaining: 6m 17s
57:	learn: 0.5630167	total: 23.2s	remaining: 6m 16s
58:	learn: 0.5626738	total: 23.6s	remaining: 6m 16s
59:	learn: 0.5624220	total: 24s	remaining: 6m 15s
60:	learn: 0.5621162	total: 24.4s	remaining: 6m 15s
61:	learn: 0.5618397	total: 24.8s	remaining: 6m 15s
62:	learn: 0.5614197	total: 25.2s	remaining: 6m 15s
63:	learn: 0.5612125	total: 25.6s	remaining: 6m 14s
64:	learn: 0.5609994	total: 26s	remaining: 6m 13s
65:	learn: 0.5607461	total: 26.4s	remaining: 6m 13s
66:	learn: 0.5604906	total: 26.8s	remaining: 6m 13s
67:	learn: 0.5602394	total: 27.2s	remaining: 6m 12s
68:	learn: 0.5600928	total: 27.6s	remaining: 6m 12s
69:	learn: 0.5598016	total: 28s	remaining: 6m 12s
70:	learn: 0.5594514	total: 28.4s	remaining: 6m 11s
71:	learn: 0.5591840	total: 28.8s	remaining: 6m 11s
72:	learn: 0.5588353	total: 29.2s	remaining: 6m 11s
73:	learn: 0.5586007	total: 29.7s	remaining: 6m 11s
74:	learn: 0.5584316	total: 30.1s	remaining: 6m 10s
75:	learn: 0.5582558	total: 30.5s	remaining: 6m 10s
76:	learn: 0.5580457	total: 30.9s	remaining: 6m 10s
77:	learn: 0.5578607	total: 31.3s	remaining: 6m 10s
78:	learn: 0.5575661	total: 31.7s	remaining: 6m 9s
79:	learn: 0.5573194	total: 32.1s	remaining: 6m 9s
80:	learn: 0.5570864	total: 32.5s	remaining: 6m 8s
81:	learn: 0.5568688	total: 32.9s	remaining: 6m 8s
82:	learn: 0.5566540	total: 33.3s	remaining: 6m 8s
83:	learn: 0.5564472	total: 33.7s	remaining: 6m 7s
84:	learn: 0.5562455	total: 34.2s	remaining: 6m 7s
85:	learn: 0.5560178	total: 34.6s	remaining: 6m 7s
86:	learn: 0.5558472	total: 35s	remaining: 6m 6s
87:	learn: 0.5556826	total: 35.4s	remaining: 6m 6s
88:	learn: 0.5555297	total: 35.8s	remaining: 6m 6s
89:	learn: 0.5553269	total: 36.2s	remaining: 6m 5s
90:	learn: 0.5550925	total: 36.6s	remaining: 6m 5s
91:	learn: 0.5549573	total: 37s	remaining: 6m 5s
92:	learn: 0.5548082	total: 37.4s	remaining: 6m 5s
93:	learn: 0.5545277	total: 37.8s	remaining: 6m 4s
94:	learn: 0.5543859	total: 38.2s	remaining: 6m 4s
95:	learn: 0.5542144	total: 38.7s	remaining: 6m 4s
96:	learn: 0.5540407	total: 39.1s	remaining: 6m 3s
97:	learn: 0.5538948	total: 39.5s	remaining: 6m 3s
98:	learn: 0.5537352	total: 39.9s	remaining: 6m 3s
99:	learn: 0.5535868	total: 40.3s	remaining: 6m 2s
100:	learn: 0.5534005	total: 40.7s	remaining: 6m 2s
101:	learn: 0.5532994	total: 41.1s	remaining: 6m 2s
102:	learn: 0.5531376	total: 41.5s	remaining: 6m 1s
103:	learn: 0.5529633	total: 42s	remaining: 6m 1s
104:	learn: 0.5528165	total: 42.4s	remaining: 6m 1s
105:	learn: 0.5526899	total: 42.8s	remaining: 6m
106:	learn: 0.5525169	total: 43.2s	remaining: 6m
107:	learn: 0.5524223	total: 43.6s	remaining: 6m
108:	learn: 0.5522665	total: 43.9s	remaining: 5m 59s
109:	learn: 0.5521480	total: 44.3s	remaining: 5m 58s
110:	learn: 0.5520387	total: 44.8s	remaining: 5m 58s
111:	learn: 0.5518736	total: 45.2s	remaining: 5m 58s
112:	learn: 0.5517317	total: 45.6s	remaining: 5m 57s
113:	learn: 0.5515532	total: 46s	remaining: 5m 57s
114:	learn: 0.5514210	total: 46.4s	remaining: 5m 57s
115:	learn: 0.5513995	total: 46.5s	remaining: 5m 54s
116:	learn: 0.5512398	total: 46.9s	remaining: 5m 53s
117:	learn: 0.5510374	total: 47.3s	remaining: 5m 53s
118:	learn: 0.5508655	total: 47.7s	remaining: 5m 53s
119:	learn: 0.5507862	total: 48.1s	remaining: 5m 52s
120:	learn: 0.5506270	total: 48.5s	remaining: 5m 52s
121:	learn: 0.5505298	total: 48.9s	remaining: 5m 52s
122:	learn: 0.5504120	total: 49.3s	remaining: 5m 51s
123:	learn: 0.5502102	total: 49.8s	remaining: 5m 51s
124:	learn: 0.5500410	total: 50.2s	remaining: 5m 51s
125:	learn: 0.5499464	total: 50.6s	remaining: 5m 50s
126:	learn: 0.5497833	total: 51s	remaining: 5m 50s
127:	learn: 0.5496249	total: 51.4s	remaining: 5m 50s
128:	learn: 0.5494529	total: 51.8s	remaining: 5m 49s
129:	learn: 0.5493706	total: 52.2s	remaining: 5m 49s
130:	learn: 0.5492358	total: 52.6s	remaining: 5m 49s
131:	learn: 0.5490398	total: 53s	remaining: 5m 48s
132:	learn: 0.5489704	total: 53.4s	remaining: 5m 47s
133:	learn: 0.5488247	total: 53.8s	remaining: 5m 47s
134:	learn: 0.5486329	total: 54.2s	remaining: 5m 47s
135:	learn: 0.5485222	total: 54.6s	remaining: 5m 46s
136:	learn: 0.5484322	total: 55s	remaining: 5m 46s
137:	learn: 0.5483524	total: 55.4s	remaining: 5m 46s
138:	learn: 0.5482535	total: 55.8s	remaining: 5m 45s
139:	learn: 0.5481370	total: 56.2s	remaining: 5m 45s
140:	learn: 0.5480182	total: 56.6s	remaining: 5m 45s
141:	learn: 0.5479243	total: 57.1s	remaining: 5m 44s
142:	learn: 0.5478334	total: 57.5s	remaining: 5m 44s
143:	learn: 0.5477448	total: 57.9s	remaining: 5m 44s
144:	learn: 0.5476041	total: 58.3s	remaining: 5m 43s
145:	learn: 0.5474559	total: 58.7s	remaining: 5m 43s
146:	learn: 0.5473367	total: 59.1s	remaining: 5m 43s
147:	learn: 0.5471897	total: 59.5s	remaining: 5m 42s
148:	learn: 0.5470864	total: 59.9s	remaining: 5m 42s
149:	learn: 0.5469220	total: 1m	remaining: 5m 41s
150:	learn: 0.5468447	total: 1m	remaining: 5m 41s
151:	learn: 0.5467495	total: 1m 1s	remaining: 5m 41s
152:	learn: 0.5466034	total: 1m 1s	remaining: 5m 40s
153:	learn: 0.5464385	total: 1m 1s	remaining: 5m 40s
154:	learn: 0.5463731	total: 1m 2s	remaining: 5m 40s
155:	learn: 0.5463220	total: 1m 2s	remaining: 5m 39s
156:	learn: 0.5462113	total: 1m 3s	remaining: 5m 39s
157:	learn: 0.5460966	total: 1m 3s	remaining: 5m 38s
158:	learn: 0.5460157	total: 1m 4s	remaining: 5m 38s
159:	learn: 0.5458493	total: 1m 4s	remaining: 5m 37s
160:	learn: 0.5457209	total: 1m 4s	remaining: 5m 37s
161:	learn: 0.5456557	total: 1m 5s	remaining: 5m 37s
162:	learn: 0.5455561	total: 1m 5s	remaining: 5m 36s
163:	learn: 0.5454385	total: 1m 5s	remaining: 5m 36s
164:	learn: 0.5453429	total: 1m 6s	remaining: 5m 36s
165:	learn: 0.5452393	total: 1m 6s	remaining: 5m 35s
166:	learn: 0.5451452	total: 1m 7s	remaining: 5m 35s
167:	learn: 0.5450395	total: 1m 7s	remaining: 5m 34s
168:	learn: 0.5449501	total: 1m 8s	remaining: 5m 34s
169:	learn: 0.5448719	total: 1m 8s	remaining: 5m 34s
170:	learn: 0.5447259	total: 1m 8s	remaining: 5m 33s
171:	learn: 0.5446254	total: 1m 9s	remaining: 5m 33s
172:	learn: 0.5445496	total: 1m 9s	remaining: 5m 33s
173:	learn: 0.5444230	total: 1m 10s	remaining: 5m 32s
174:	learn: 0.5442956	total: 1m 10s	remaining: 5m 32s
175:	learn: 0.5442676	total: 1m 10s	remaining: 5m 31s
176:	learn: 0.5441588	total: 1m 11s	remaining: 5m 31s
177:	learn: 0.5440599	total: 1m 11s	remaining: 5m 30s
178:	learn: 0.5439076	total: 1m 12s	remaining: 5m 30s
179:	learn: 0.5437690	total: 1m 12s	remaining: 5m 30s
180:	learn: 0.5437217	total: 1m 12s	remaining: 5m 29s
181:	learn: 0.5435860	total: 1m 13s	remaining: 5m 29s
182:	learn: 0.5435241	total: 1m 13s	remaining: 5m 28s
183:	learn: 0.5434557	total: 1m 14s	remaining: 5m 28s
184:	learn: 0.5433450	total: 1m 14s	remaining: 5m 27s
185:	learn: 0.5431983	total: 1m 14s	remaining: 5m 27s
186:	learn: 0.5431446	total: 1m 15s	remaining: 5m 27s
187:	learn: 0.5430396	total: 1m 15s	remaining: 5m 26s
188:	learn: 0.5429256	total: 1m 16s	remaining: 5m 26s
189:	learn: 0.5428395	total: 1m 16s	remaining: 5m 25s
190:	learn: 0.5427236	total: 1m 16s	remaining: 5m 25s
191:	learn: 0.5425718	total: 1m 17s	remaining: 5m 25s
192:	learn: 0.5424930	total: 1m 17s	remaining: 5m 24s
193:	learn: 0.5423805	total: 1m 18s	remaining: 5m 24s
194:	learn: 0.5422728	total: 1m 18s	remaining: 5m 23s
195:	learn: 0.5421231	total: 1m 18s	remaining: 5m 23s
196:	learn: 0.5420591	total: 1m 19s	remaining: 5m 23s
197:	learn: 0.5419122	total: 1m 19s	remaining: 5m 22s
198:	learn: 0.5418130	total: 1m 20s	remaining: 5m 22s
199:	learn: 0.5416922	total: 1m 20s	remaining: 5m 21s
200:	learn: 0.5416296	total: 1m 20s	remaining: 5m 21s
201:	learn: 0.5415581	total: 1m 21s	remaining: 5m 20s
202:	learn: 0.5414606	total: 1m 21s	remaining: 5m 20s
203:	learn: 0.5413649	total: 1m 22s	remaining: 5m 20s
204:	learn: 0.5412897	total: 1m 22s	remaining: 5m 19s
205:	learn: 0.5412000	total: 1m 22s	remaining: 5m 19s
206:	learn: 0.5411288	total: 1m 23s	remaining: 5m 19s
207:	learn: 0.5409950	total: 1m 23s	remaining: 5m 18s
208:	learn: 0.5408621	total: 1m 24s	remaining: 5m 18s
209:	learn: 0.5408205	total: 1m 24s	remaining: 5m 17s
210:	learn: 0.5406336	total: 1m 24s	remaining: 5m 17s
211:	learn: 0.5404703	total: 1m 25s	remaining: 5m 16s
212:	learn: 0.5402755	total: 1m 25s	remaining: 5m 16s
213:	learn: 0.5401574	total: 1m 26s	remaining: 5m 16s
214:	learn: 0.5400041	total: 1m 26s	remaining: 5m 15s
215:	learn: 0.5398646	total: 1m 26s	remaining: 5m 15s
216:	learn: 0.5397551	total: 1m 27s	remaining: 5m 14s
217:	learn: 0.5397029	total: 1m 27s	remaining: 5m 14s
218:	learn: 0.5396057	total: 1m 28s	remaining: 5m 13s
219:	learn: 0.5394658	total: 1m 28s	remaining: 5m 13s
220:	learn: 0.5392435	total: 1m 28s	remaining: 5m 13s
221:	learn: 0.5390647	total: 1m 29s	remaining: 5m 12s
222:	learn: 0.5388941	total: 1m 29s	remaining: 5m 12s
223:	learn: 0.5387026	total: 1m 29s	remaining: 5m 11s
224:	learn: 0.5385195	total: 1m 30s	remaining: 5m 11s
225:	learn: 0.5383931	total: 1m 30s	remaining: 5m 10s
226:	learn: 0.5382410	total: 1m 31s	remaining: 5m 10s
227:	learn: 0.5380881	total: 1m 31s	remaining: 5m 10s
228:	learn: 0.5379979	total: 1m 32s	remaining: 5m 9s
229:	learn: 0.5379068	total: 1m 32s	remaining: 5m 9s
230:	learn: 0.5377897	total: 1m 32s	remaining: 5m 8s
231:	learn: 0.5376482	total: 1m 33s	remaining: 5m 8s
232:	learn: 0.5374473	total: 1m 33s	remaining: 5m 8s
233:	learn: 0.5372668	total: 1m 34s	remaining: 5m 7s
234:	learn: 0.5371756	total: 1m 34s	remaining: 5m 7s
235:	learn: 0.5370165	total: 1m 34s	remaining: 5m 7s
236:	learn: 0.5368856	total: 1m 35s	remaining: 5m 6s
237:	learn: 0.5366926	total: 1m 35s	remaining: 5m 6s
238:	learn: 0.5365260	total: 1m 36s	remaining: 5m 5s
239:	learn: 0.5363345	total: 1m 36s	remaining: 5m 5s
240:	learn: 0.5361738	total: 1m 36s	remaining: 5m 5s
241:	learn: 0.5359453	total: 1m 37s	remaining: 5m 4s
242:	learn: 0.5357068	total: 1m 37s	remaining: 5m 4s
243:	learn: 0.5356632	total: 1m 38s	remaining: 5m 3s
244:	learn: 0.5355413	total: 1m 38s	remaining: 5m 3s
245:	learn: 0.5353443	total: 1m 38s	remaining: 5m 3s
246:	learn: 0.5352364	total: 1m 39s	remaining: 5m 2s
247:	learn: 0.5350643	total: 1m 39s	remaining: 5m 2s
248:	learn: 0.5348839	total: 1m 40s	remaining: 5m 1s
249:	learn: 0.5347099	total: 1m 40s	remaining: 5m 1s
250:	learn: 0.5345258	total: 1m 40s	remaining: 5m 1s
251:	learn: 0.5343859	total: 1m 41s	remaining: 5m
252:	learn: 0.5341657	total: 1m 41s	remaining: 5m
253:	learn: 0.5339868	total: 1m 42s	remaining: 5m
254:	learn: 0.5339205	total: 1m 42s	remaining: 4m 59s
255:	learn: 0.5338121	total: 1m 42s	remaining: 4m 59s
256:	learn: 0.5336020	total: 1m 43s	remaining: 4m 58s
257:	learn: 0.5334607	total: 1m 43s	remaining: 4m 58s
258:	learn: 0.5333393	total: 1m 44s	remaining: 4m 58s
259:	learn: 0.5331887	total: 1m 44s	remaining: 4m 57s
260:	learn: 0.5330339	total: 1m 45s	remaining: 4m 57s
261:	learn: 0.5329625	total: 1m 45s	remaining: 4m 56s
262:	learn: 0.5327224	total: 1m 45s	remaining: 4m 56s
263:	learn: 0.5325725	total: 1m 46s	remaining: 4m 56s
264:	learn: 0.5323665	total: 1m 46s	remaining: 4m 55s
265:	learn: 0.5321939	total: 1m 47s	remaining: 4m 55s
266:	learn: 0.5320035	total: 1m 47s	remaining: 4m 54s
267:	learn: 0.5318672	total: 1m 47s	remaining: 4m 54s
268:	learn: 0.5316731	total: 1m 48s	remaining: 4m 54s
269:	learn: 0.5314870	total: 1m 48s	remaining: 4m 53s
270:	learn: 0.5313277	total: 1m 49s	remaining: 4m 53s
271:	learn: 0.5311011	total: 1m 49s	remaining: 4m 52s
272:	learn: 0.5310093	total: 1m 49s	remaining: 4m 52s
273:	learn: 0.5307951	total: 1m 50s	remaining: 4m 52s
274:	learn: 0.5306077	total: 1m 50s	remaining: 4m 51s
275:	learn: 0.5304636	total: 1m 51s	remaining: 4m 51s
276:	learn: 0.5302707	total: 1m 51s	remaining: 4m 50s
277:	learn: 0.5301913	total: 1m 51s	remaining: 4m 50s
278:	learn: 0.5300575	total: 1m 52s	remaining: 4m 50s
279:	learn: 0.5298568	total: 1m 52s	remaining: 4m 49s
280:	learn: 0.5297766	total: 1m 53s	remaining: 4m 49s
281:	learn: 0.5296813	total: 1m 53s	remaining: 4m 49s
282:	learn: 0.5295184	total: 1m 53s	remaining: 4m 48s
283:	learn: 0.5293598	total: 1m 54s	remaining: 4m 48s
284:	learn: 0.5292181	total: 1m 54s	remaining: 4m 47s
285:	learn: 0.5290760	total: 1m 55s	remaining: 4m 47s
286:	learn: 0.5288800	total: 1m 55s	remaining: 4m 47s
287:	learn: 0.5288395	total: 1m 55s	remaining: 4m 46s
288:	learn: 0.5286708	total: 1m 56s	remaining: 4m 46s
289:	learn: 0.5286059	total: 1m 56s	remaining: 4m 45s
290:	learn: 0.5284300	total: 1m 57s	remaining: 4m 45s
291:	learn: 0.5282478	total: 1m 57s	remaining: 4m 45s
292:	learn: 0.5281289	total: 1m 57s	remaining: 4m 44s
293:	learn: 0.5279951	total: 1m 58s	remaining: 4m 44s
294:	learn: 0.5278638	total: 1m 58s	remaining: 4m 43s
295:	learn: 0.5277392	total: 1m 59s	remaining: 4m 43s
296:	learn: 0.5275434	total: 1m 59s	remaining: 4m 43s
297:	learn: 0.5273704	total: 1m 59s	remaining: 4m 42s
298:	learn: 0.5273089	total: 2m	remaining: 4m 42s
299:	learn: 0.5271750	total: 2m	remaining: 4m 41s
300:	learn: 0.5270591	total: 2m 1s	remaining: 4m 41s
301:	learn: 0.5268745	total: 2m 1s	remaining: 4m 41s
302:	learn: 0.5267538	total: 2m 2s	remaining: 4m 40s
303:	learn: 0.5266634	total: 2m 2s	remaining: 4m 40s
304:	learn: 0.5264865	total: 2m 2s	remaining: 4m 39s
305:	learn: 0.5264034	total: 2m 3s	remaining: 4m 39s
306:	learn: 0.5262813	total: 2m 3s	remaining: 4m 39s
307:	learn: 0.5261165	total: 2m 4s	remaining: 4m 38s
308:	learn: 0.5258974	total: 2m 4s	remaining: 4m 38s
309:	learn: 0.5258077	total: 2m 4s	remaining: 4m 37s
310:	learn: 0.5256425	total: 2m 5s	remaining: 4m 37s
311:	learn: 0.5255132	total: 2m 5s	remaining: 4m 37s
312:	learn: 0.5253706	total: 2m 6s	remaining: 4m 36s
313:	learn: 0.5252163	total: 2m 6s	remaining: 4m 36s
314:	learn: 0.5250505	total: 2m 6s	remaining: 4m 35s
315:	learn: 0.5248590	total: 2m 7s	remaining: 4m 35s
316:	learn: 0.5247231	total: 2m 7s	remaining: 4m 35s
317:	learn: 0.5245628	total: 2m 8s	remaining: 4m 34s
318:	learn: 0.5244051	total: 2m 8s	remaining: 4m 34s
319:	learn: 0.5242902	total: 2m 8s	remaining: 4m 33s
320:	learn: 0.5241498	total: 2m 9s	remaining: 4m 33s
321:	learn: 0.5240787	total: 2m 9s	remaining: 4m 33s
322:	learn: 0.5239489	total: 2m 10s	remaining: 4m 32s
323:	learn: 0.5237763	total: 2m 10s	remaining: 4m 32s
324:	learn: 0.5236819	total: 2m 10s	remaining: 4m 31s
325:	learn: 0.5235984	total: 2m 11s	remaining: 4m 31s
326:	learn: 0.5234842	total: 2m 11s	remaining: 4m 31s
327:	learn: 0.5233910	total: 2m 12s	remaining: 4m 30s
328:	learn: 0.5232284	total: 2m 12s	remaining: 4m 30s
329:	learn: 0.5230670	total: 2m 12s	remaining: 4m 29s
330:	learn: 0.5229989	total: 2m 13s	remaining: 4m 29s
331:	learn: 0.5228875	total: 2m 13s	remaining: 4m 29s
332:	learn: 0.5227480	total: 2m 14s	remaining: 4m 28s
333:	learn: 0.5226317	total: 2m 14s	remaining: 4m 28s
334:	learn: 0.5225975	total: 2m 14s	remaining: 4m 27s
335:	learn: 0.5224311	total: 2m 15s	remaining: 4m 27s
336:	learn: 0.5223459	total: 2m 15s	remaining: 4m 27s
337:	learn: 0.5221935	total: 2m 16s	remaining: 4m 26s
338:	learn: 0.5220276	total: 2m 16s	remaining: 4m 26s
339:	learn: 0.5219239	total: 2m 16s	remaining: 4m 25s
340:	learn: 0.5217634	total: 2m 17s	remaining: 4m 25s
341:	learn: 0.5216153	total: 2m 17s	remaining: 4m 25s
342:	learn: 0.5214760	total: 2m 18s	remaining: 4m 24s
343:	learn: 0.5213639	total: 2m 18s	remaining: 4m 24s
344:	learn: 0.5212470	total: 2m 19s	remaining: 4m 23s
345:	learn: 0.5211773	total: 2m 19s	remaining: 4m 23s
346:	learn: 0.5209952	total: 2m 19s	remaining: 4m 23s
347:	learn: 0.5208922	total: 2m 20s	remaining: 4m 22s
348:	learn: 0.5208281	total: 2m 20s	remaining: 4m 22s
349:	learn: 0.5207473	total: 2m 21s	remaining: 4m 21s
350:	learn: 0.5206327	total: 2m 21s	remaining: 4m 21s
351:	learn: 0.5205743	total: 2m 21s	remaining: 4m 21s
352:	learn: 0.5203927	total: 2m 22s	remaining: 4m 20s
353:	learn: 0.5202691	total: 2m 22s	remaining: 4m 20s
354:	learn: 0.5201890	total: 2m 23s	remaining: 4m 19s
355:	learn: 0.5200815	total: 2m 23s	remaining: 4m 19s
356:	learn: 0.5199072	total: 2m 23s	remaining: 4m 19s
357:	learn: 0.5197779	total: 2m 24s	remaining: 4m 18s
358:	learn: 0.5196735	total: 2m 24s	remaining: 4m 18s
359:	learn: 0.5195104	total: 2m 25s	remaining: 4m 17s
360:	learn: 0.5194117	total: 2m 25s	remaining: 4m 17s
361:	learn: 0.5192796	total: 2m 25s	remaining: 4m 17s
362:	learn: 0.5191651	total: 2m 26s	remaining: 4m 16s
363:	learn: 0.5189846	total: 2m 26s	remaining: 4m 16s
364:	learn: 0.5188410	total: 2m 27s	remaining: 4m 15s
365:	learn: 0.5187237	total: 2m 27s	remaining: 4m 15s
366:	learn: 0.5185605	total: 2m 27s	remaining: 4m 15s
367:	learn: 0.5184883	total: 2m 28s	remaining: 4m 14s
368:	learn: 0.5184013	total: 2m 28s	remaining: 4m 14s
369:	learn: 0.5182668	total: 2m 29s	remaining: 4m 13s
370:	learn: 0.5181420	total: 2m 29s	remaining: 4m 13s
371:	learn: 0.5179936	total: 2m 29s	remaining: 4m 13s

In [101]:
with open('df_anal2.pickle', 'wb') as f:
            pickle.dump(df_anal2, f)
with open('df_no_scailing_2.pickle', 'wb') as f:
            pickle.dump(df_no_scailing_2, f)